-- RC Atölyesi — Başlangıç İçeriği (Örnek 18 Soru + Çözüm)
-- ============================================================
-- ÖNEMLİ — ÇALIŞTIRMADAN ÖNCE:
-- 1) Siteye normal kayıt ekranından "RC Atölyesi Ekibi" (veya beğendiğin
--    başka bir isim) kullanıcı adıyla YENİ BİR HESAP aç.
-- 2) Supabase panelinde: Table Editor -> profiles tablosu -> az önce
--    açtığın hesabı bul -> "id" sütunundaki UUID'i kopyala.
-- 3) Aşağıdaki dosyada geçen HER "EKIP_UUID_BURAYA" yazan yeri o UUID
--    ile değiştir (bulundur-değiştir ile tek seferde yapabilirsin).
-- 4) SQL Editor -> New query -> tamamını yapıştır -> Run.
--
-- Bu betik 18 örnek soru ekliyor, hepsini "çözüldü" (solved) olarak
-- işaretliyor ve her birine kabul edilmiş bir cevap ekliyor. Beğenirsen
-- aynı formatta kalanını (100'e tamamlayacak şekilde) hazırlarım.
-- ============================================================

-- 1) Traxxas Maxx — motor aşırı ısınıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('959c1477-0531-4b11-8098-7eb2f25789a8', 'EKIP_UUID_BURAYA', 'Motor 3S''te aşırı ısınıyor, birkaç dakikada dokunulmaz hale geliyor', 'Traxxas', 'Maxx', 'motor', 'araba', 'Traxxas Maxx''i 3S lipo ile kullanıyorum. İlk 5-6 dakika sorun yok ama sonra motor gövdesi elimi yakacak kadar ısınıyor ve güç kesiliyor (termal koruma devreye giriyor gibi). Pinyon dişli ile spur dişli arasındaki boşluğu kontrol ettim, normal görünüyor. Sorun ne olabilir?', 'solved', 'traxxas-maxx-motor-asiri-isiniyor-x7k2p9', now() - interval '19 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '959c1477-0531-4b11-8098-7eb2f25789a8', 'EKIP_UUID_BURAYA', 'Bu şikayeti çok sık duyuyoruz, genelde üç şeyden biri: 1) Pinyon-spur boşluğu görünüşte normal olsa da bir kağıt kalınlığı fazla sıkı olabilir, bir ince kağıt (business kart) payı bırakarak tekrar ayarla. 2) ESC''nin motor soğutma fanı varsa fan bağlantısını kontrol et, çoğu zaman fan konnektörü gevşer ve fark edilmez. 3) 3S''te fabrika pinyonu bazı setlerde agresif kalabilir, 1-2 diş küçük pinyona geçmek ısınmayı belirgin şekilde azaltır. Ayrıca sürüş sonrası motoru hemen kapatmak yerine 30 saniye rölantide bekletip soğutmasına izin ver, ani kapatma termal stresi artırıyor.', true, now() - interval '18 days');

-- 2) Arrma Kraton — ESC bip sesi çıkarıp çalışmıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('bc3fa12e-8ffa-43b7-b97d-41f1cb52a940', 'EKIP_UUID_BURAYA', 'ESC açılışta 5 kere bip sesi çıkarıp gaz vermiyor', 'Arrma', 'Kraton', 'esc', 'araba', 'Aracı açtığımda ESC 5 kısa bip sesi çıkarıyor ve motor hiç tepki vermiyor, sadece "tık" sesi geliyor gaz verince. Batarya tam dolu, konnektörler temiz. Kumandayı da fabrika ayarlarına resetledim ama değişmedi.', 'solved', 'arrma-kraton-esc-5-bip-calismiyor-m3v8q1', now() - interval '17 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'bc3fa12e-8ffa-43b7-b97d-41f1cb52a940', 'EKIP_UUID_BURAYA', '5 bip sesi çoğu marka ESC''de "gaz kolu merkezde algılanamadı" hata koduna denk geliyor — yani ESC, kumandanın nötr sinyalini göremiyor. Genelde sebebi kumandanın throttle trimini sıfırlamamak veya ESC''yi kalibre etmeden değiştirmiş olmak. Çözüm: ESC''yi kalibrasyon moduna al (genelde açma düğmesine uzun basılı tutmak), gaz kolunu tam ileri-tam geri-nötr sırasıyla hareket ettirip ESC''ye yeniden öğret. Kalibrasyon sonrası çalışmıyorsa alıcı (receiver) ile ESC arasındaki 3 pinli kabloyu ters takmış olabilirsin, yön işaretine bak.', true, now() - interval '16 days');

-- 3) HPI Savage — direksiyon servosu geç tepki veriyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('655c9c64-b33d-436b-8f13-943227c707b9', 'EKIP_UUID_BURAYA', 'Direksiyon servosu komuta 1 saniye gecikmeyle cevap veriyor', 'HPI', 'Savage XL', 'servo', 'araba', 'Kumandayı çevirdiğimde tekerlekler hemen değil, yaklaşık 1 saniye sonra dönüyor. Servo ısınmıyor, ses de yapmıyor ama tepki süresi çok yavaş. Yeni bir araç, ilk kullanımım.', 'solved', 'hpi-savage-servo-gecikme-t5n0w4', now() - interval '15 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '655c9c64-b33d-436b-8f13-943227c707b9', 'EKIP_UUID_BURAYA', 'Gerçek bir gecikme değilse (yani servo aslında normal hızda ama SEN geç fark ediyorsan) bu genelde kumanda ile alıcı arasındaki "binding" (eşleştirme) sorunudur — kumanda ve alıcı iki farklı sinyal protokolünde takılı kalmış olabilir, tekrar bind işlemi yapman gerekir. Eğer servo gerçekten yavaş hareket ediyorsa: 1) Servo hızı (speed) ayarı kumandada kısılmış olabilir, kumanda menüsünden kontrol et. 2) Servoya giden voltaj düşükse (zayıf BEC veya düşük voltajlı alıcı bataryası) servo yavaşlar, voltajı ölçtür. 3) Yeni araçlarda bazen servo horn (kolu) mekanik olarak sıkışmış/sürtünüyor olabilir, direksiyon linkajını elle çevirip sertlik var mı kontrol et.', true, now() - interval '14 days');

-- 4) Losi 22S — batarya şarj olmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('3064596a-084b-48a5-ba04-c146787a617d', 'EKIP_UUID_BURAYA', 'Lipo batarya şarj cihazına takılınca "hata" veriyor, hiç şarj olmuyor', 'Losi', '22S', 'batarya', 'araba', '2S 5000mAh lipo bataryam şarj cihazına (imax b6 benzeri) takılınca birkaç saniye sonra "error" yazıp şarjı durduruyor. Batarya gözle görülür şekilde şişmiş değil ama geçen hafta yarı boş bırakmıştım uzun süre.', 'solved', 'losi-lipo-sarj-hatasi-r8j3z6', now() - interval '13 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '3064596a-084b-48a5-ba04-c146787a617d', 'EKIP_UUID_BURAYA', 'Bu senaryoda en olası sebep: bataryanın hücrelerinden biri "derin deşarj" seviyesinin altına düşmüş (lipo''lar boş bırakılınca bu olur). Şarj cihazları güvenlik için aşırı düşük voltajlı hücreyi şarj etmeyi reddeder çünkü yangın riski var. ÖNEMLİ GÜVENLİK UYARISI: Böyle bir bataryayı "zorla" şarj etmeye çalışma (bazı cihazlarda bypass modu var ama bunu sadece deneyimliysen ve bataryayı yanıcı olmayan bir torbada, gözetim altında yaparsan kullan). En güvenlisi: hücre dengesi bozulmuş, şişmiş veya derin deşarj olmuş lipoyu artık kullanma, güvenli şekilde imha et (çoğu hobi mağazası tuzlu suda bekletip imha kabul ediyor). Gelecekte bunu önlemek için bataryayı asla %20''nin altına indirmeden depola ve uzun süre kullanmayacaksan "storage charge" (depolama şarjı) seviyesinde tut.', true, now() - interval '12 days');

-- 5) Traxxas Slash — şasi vidaları sürekli gevşiyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('b6719198-b78d-4eca-b402-721ce08fe3a9', 'EKIP_UUID_BURAYA', 'Her sürüşten sonra süspansiyon vidaları gevşemiş oluyor', 'Traxxas', 'Slash 2WD', 'sasi', 'araba', 'Her koşudan sonra süspansiyon pivot vidalarını ve şasi vidalarını kontrol ediyorum, neredeyse hepsi bir tur gevşemiş oluyor. Loctite kullanmıyordum, acaba bu mu sebep?', 'solved', 'traxxas-slash-vidalar-gevsiyor-k2h7l0', now() - interval '11 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'b6719198-b78d-4eca-b402-721ce08fe3a9', 'EKIP_UUID_BURAYA', 'Evet, birebir bu — titreşim ve darbe altında çalışan RC araçlarda vida gevşemesi çok normaldir ve çözümü tam olarak dişli sabitleyici (thread locker / Loctite 243 mavi kapak) kullanmak. Kırmızı (Loctite 271) kullanma, o kalıcıdır ve söktüğünde vida başını sıyırabilirsin; mavi olan yeterince güçlü ama tekrar sökülebilir. Her vidaya minik bir damla sürüp 24 saat kurumaya bırak. Ayrıca süspansiyon pivot pinlerinde E-clip''ler varsa onların da tam oturduğundan emin ol, gevşek E-clip vida gevşemesini hızlandırır.', true, now() - interval '10 days');

-- 6) Redcat Volcano — lastikler çok çabuk aşınıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('7b803cc5-9d63-46d2-82b7-55925e81f4dd', 'EKIP_UUID_BURAYA', 'Arka lastikler 2-3 koşuda düzleşiyor, normal mi?', 'Redcat', 'Volcano', 'lastik', 'araba', 'Asfaltta sürüyorum genelde, arka lastiklerin dişleri 2-3 koşu sonra düzleşmeye başladı. Ön lastikler daha iyi durumda. Sürüş tarzım agresif sayılmaz.', 'solved', 'redcat-volcano-lastik-asinma-p4d9x2', now() - interval '9 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '7b803cc5-9d63-46d2-82b7-55925e81f4dd', 'EKIP_UUID_BURAYA', 'Bu beklenen bir durum aslında: 1) Çoğu RC lastiği (özellikle off-road/kabartmalı desenli) toprak/çim için tasarlanır, asfalt gibi sert ve aşındırıcı zeminlerde çok daha hızlı yıpranır — özel "on-road" bileşimli lastik kullanman gerekir. 2) Arka lastiklerin daha hızlı aşınması normal çünkü güç arkadan veriliyor (2WD/4WD fark etmeksizin arka aks genelde daha çok tork taşıyor), yani arka lastikte daha fazla sürtünme/spin oluyor. 3) Agresif olmasan bile ani gaz-fren geçişleri (özellikle kalkışta tam gaz) asfaltta lastik yakar. Çözüm: asfalt için sert bileşimli (harder compound) lastik almak, ya da sürüşü çim/toprak parkurlara kaydırmak.', true, now() - interval '8 days');

-- 7) WLtoys 144001 — diferansiyelden ses geliyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('987cadc9-b9e7-4668-a156-8fbfef80d637', 'EKIP_UUID_BURAYA', 'Viraja girince arkadan gıcırtılı/öğütme sesi geliyor', 'WLtoys', '144001', 'sasi', 'araba', 'Düz giderken sessiz ama keskin viraja girince arka taraftan metal öğütme sesine benzer bir ses geliyor. Diferansiyel yağı hiç değiştirmedim, araç 3 aylık.', 'solved', 'wltoys-144001-diferansiyel-sesi-y6b1n8', now() - interval '7 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '987cadc9-b9e7-4668-a156-8fbfef80d637', 'EKIP_UUID_BURAYA', 'Bu tam olarak diferansiyel gres/yağ eksikliğinin klasik belirtisi — viraja girince tekerlekler farklı hızlarda dönmeye çalışıyor, diferansiyel içindeki dişliler bu farkı karşılıyor ve yağsız/az yağlı kalınca metal-metal sürtünmesi ses yapıyor. Bütçe RC araçlarda (WLtoys, XLH gibi) fabrika diferansiyel gresi genelde az veya düşük kalitelidir. Çözümü: diferansiyel kapağını aç, içindeki dişlileri temizle (eski gresi çıkar), silikon bazlı diferansiyel gresi (ör. 100.000 cst) ile dişli boşluklarını iyice doldur, tekrar kapat. Bu işlemi her 2-3 ayda bir rutin bakım olarak yapman öneriyoruz, özellikle toprak/kum ortamında sürüyorsan.', true, now() - interval '6 days');

-- 8) Arrma Typhon — frenler tutmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('e4a74135-fc61-4ddd-9fea-864c47b09433', 'EKIP_UUID_BURAYA', 'Fren neredeyse hiç tutmuyor, araç kaymaya devam ediyor', 'Arrma', 'Typhon', 'diger', 'araba', 'Gaz kolunu geri çekince (fren) araç neredeyse hiç yavaşlamıyor, özellikle yüksek hızda durması çok uzun sürüyor. ESC ayarlarına bakmadım henüz, fabrika ayarında.', 'solved', 'arrma-typhon-fren-tutmuyor-w3g5c7', now() - interval '5 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'e4a74135-fc61-4ddd-9fea-864c47b09433', 'EKIP_UUID_BURAYA', 'Sensored/sensorless fırçasız ESC''lerin çoğunda fren gücü (brake force) fabrika ayarında düşük veya %0 gelir, güvenlik amaçlı. ESC''nin programlama kartı veya kendi düğmesiyle "Brake Force" ayarını yükseltmen gerekiyor (genelde %50-100 arası öneriyoruz, tam %100 bazı yüzeylerde aracı takla attırabilir dikkatli artır). Ayrıca "Drag Brake" (gaz bırakınca otomatik hafif fren) ayarı da varsa açman sürüşü belirgin iyileştirir. Ayarları değiştirdikten sonra hâlâ zayıfsa, ESC-motor bağlantısındaki 3 kablodan biri gevşemiş olabilir, konnektörleri kontrol et.', true, now() - interval '4 days');

-- 9) DJI benzeri drone — havada titriyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('510fe7c2-b5d4-4adf-8dc2-2b6104518f53', 'EKIP_UUID_BURAYA', 'Havada dururken hafif hafif titriyor, görüntüde de bu titreşim çıkıyor', 'DJI', 'Mini benzeri (jenerik)', 'motor', 'drone', 'Sabit yükseklikte dururken drone hafifçe titriyor, kamera görüntüsünde de küçük bir "jitter" var. Pervaneler yeni ve dengeli görünüyor.', 'solved', 'drone-havada-titriyor-motor-t9m2r5', now() - interval '19 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '510fe7c2-b5d4-4adf-8dc2-2b6104518f53', 'EKIP_UUID_BURAYA', 'Pervaneler gözle dengeli görünse de mikro dengesizlikler titreşime yol açabilir — bir pervane dengeleyici (propeller balancer) ile test et, çoğu zaman gözle fark edilmeyen 1-2 gramlık fark bile titreşim yaratır. Diğer olası sebepler: 1) Motor yatağına toz/kum kaçmış olabilir, motoru elle çevirip pürüzsüz dönüyor mu kontrol et. 2) Gövde vidalarından biri gevşemiş olabilir, tüm motor tutucu vidalarını kontrol et. 3) Eğer titreşim sadece görüntüde çıkıyorsa (drone''un kendisi sakin ama video titrek) kamera gimbal''ının titreşim emici (vibration damper) lastikleri sertleşmiş/yıpranmış olabilir, bunlar zamanla sertleşir ve değişmesi gerekir.', true, now() - interval '18 days');

-- 10) FPV drone — GPS kilidi alamıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a95f6c71-0b8e-45ac-8d9d-57a6f3ae08f4', 'EKIP_UUID_BURAYA', 'Açık alanda bile GPS kilidi (lock) almakta çok zorlanıyor', 'Jenerik', 'GPS''li Quad', 'diger', 'drone', 'Açık bir sahada uçuruyorum ama GPS kilidi almak bazen 5 dakikayı buluyor, bazen hiç almıyor. Firmware güncel.', 'solved', 'drone-gps-kilit-alamiyor-h1s8k3', now() - interval '17 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a95f6c71-0b8e-45ac-8d9d-57a6f3ae08f4', 'EKIP_UUID_BURAYA', 'GPS kilidi alma süresi genelde şu üç şeyden etkilenir: 1) GPS anteni metal gövdeye veya elektronik kartlara çok yakın monte edilmişse sinyal karışır (elektromanyetik girişim), anteni mümkün olduğunca yukarı ve açık alana bakacak şekilde konumlandır. 2) Soğuk başlangıç (cold start) — drone''u uzun süre kapalı tuttuysan uydu almanik verisi eskimiştir, ilk kilit alışı doğal olarak uzun sürer, birkaç dakika sabırla bekle. 3) Yakınında büyük metal yapı, araba veya elektrik hattı varsa taşı, bunlar GPS sinyalini bloke eder. Ayrıca GPS modülünün üstündeki koruyucu naylonu çıkarmayı unutmuş olabilirsin, bu ilginç ama sık yapılan bir hata.', true, now() - interval '16 days');

-- 11) FPV racing drone — motor bir tanesi diğerlerinden yavaş dönüyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('0189a9cd-c9bf-4a71-992d-3850081e3394', 'EKIP_UUID_BURAYA', 'Bir motor diğerlerine göre daha yavaş/zayıf dönüyor, drone bir yöne çekiyor', 'Jenerik', 'FPV Racing Quad', 'motor', 'drone', 'Test modunda tüm motorları aynı gazda çalıştırdığımda bir motor gözle görülür şekilde daha yavaş dönüyor. Uçuşta da o yöne doğru çekme oluyor.', 'solved', 'fpv-drone-motor-yavas-donuyor-z4q7v0', now() - interval '15 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '0189a9cd-c9bf-4a71-992d-3850081e3394', 'EKIP_UUID_BURAYA', 'Bir motorun tek başına zayıf çalışması genelde ya motordadır ya da o motoru süren ESC''dedir (4in1 ESC''lerde her motorun ayrı bir çıkışı vardır). Sırayla kontrol et: 1) O motoru başka bir ESC çıkışına bağlayıp test et — eğer sorun motoru takip ediyorsa motor arızalıdır (genelde bearing/rulman aşınması veya sargılarda kısa devre), etmiyorsa ESC çıkışı arızalıdır. 2) Motor bearing''lerini elle çevirip pürüzsüzlüğünü kontrol et, sertlik/takırtı varsa rulman değişmeli. 3) Motor kablo lehimlerinden biri gevşemiş/kötü lehimlenmiş olabilir, görsel kontrol et. Ucuz motorlarda bu tip tek motor arızası oldukça sık görülür.', true, now() - interval '14 days');

-- 12) RC uçak — kalkışta motor gücü yetersiz
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('1bf5b719-3b30-49a6-a831-b3d6871f4176', 'EKIP_UUID_BURAYA', 'Kalkışta motor gücü yetersiz kalıyor, uçak havalanmakta zorlanıyor', 'Jenerik', 'Eğitim Uçağı (Trainer)', 'motor', 'ucak', 'Pistte hızlanırken motor sesinden tam güç veriyormuş gibi geliyor ama havalanmak için normalden çok daha uzun mesafe gerekiyor. Pervane yeni takıldı geçen hafta.', 'solved', 'rc-ucak-kalkis-gucu-yetersiz-b6p2m9', now() - interval '13 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '1bf5b719-3b30-49a6-a831-b3d6871f4176', 'EKIP_UUID_BURAYA', 'Pervaneyi yeni değiştirmiş olman büyük ipucu — pervane ölçüsü/açısı (pitch) motora uygun değilse güç kaybı çok belirgin olur. Kontrol listesi: 1) Yeni pervanenin çapı ve pitch değeri motor/uçak üreticisinin önerdiğiyle birebir aynı mı, değilse ya çok fazla yük biniyor (motor zorlanıyor, RPM düşüyor) ya da çok az itki üretiyor. 2) Pervane doğru yöne (doğru dönüş yönüne göre bastırma) takılı mı kontrol et, ters takılmış pervane ciddi itki kaybı yaratır. 3) Batarya voltajı tam dolu mu, düşük voltaj motor RPM''ini doğrudan düşürür. 4) Rüzgara karşı kalkış yapıyor musun, ters rüzgarda kalkış mesafesi belirgin kısalır.', true, now() - interval '12 days');

-- 13) RC uçak — kanat servosu garip hareket ediyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('42f64a18-d69b-4051-afb3-fdc791b869c9', 'EKIP_UUID_BURAYA', 'Aileron servosu ara sıra kendiliğinden ufak zıplamalar yapıyor', 'Jenerik', 'Aerobatik Uçak', 'servo', 'ucak', 'Uçuş sırasında aileron servosu bazen kısa, ani bir zıplama yapıyor, komut vermediğim halde. Radyo bağlantısı 2.4ghz, sinyal göstergesi tam.', 'solved', 'rc-ucak-servo-zipliyor-n8c3x5', now() - interval '11 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '42f64a18-d69b-4051-afb3-fdc791b869c9', 'EKIP_UUID_BURAYA', 'Bu genelde "servo glitch" olarak bilinir ve en sık sebebi elektriksel gürültü/parazit — motor kablolarının servo sinyal kablosuna çok yakın veya paralel döşenmiş olması RF/elektriksel girişim yaratır. Sinyal kablolarını motor/ESC güç kablolarından mümkün olduğunca uzak ve çapraz geçirerek döşe. Diğer olası sebepler: 1) Alıcı bataryası/BEC voltajı düşükse (özellikle birden fazla servo aynı anda çalışırken) voltaj düşüşü glitch yaratır, voltajı yük altında ölçtür. 2) Servo kablosu konnektöründe gevşeklik/temassızlık olabilir, konnektörü sık ve ısı büzüşmeli boru ile sabitle. 3) Nadiren, 2.4ghz sinyalinin kendisi başka bir cihazla (wifi, başka bir kumanda) çakışıyor olabilir, farklı bir alanda test et.', true, now() - interval '10 days');

-- 14) Align T-Rex helikopter — tail rotor titreşimi
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('d36dbbd9-33b1-4869-8757-71bcfc4d7dfc', 'EKIP_UUID_BURAYA', 'Kuyruk rotoru yüksek devirde belirgin titreşim yapıyor', 'Align', 'T-Rex 450', 'sasi', 'helikopter', 'Ana rotor sorunsuz ama kuyruk pervanesi yüksek devirde gözle görülür titreşim yapıyor, kuyruk boom''unda da hafif sallanma var.', 'solved', 'align-trex-kuyruk-titresimi-f7l4d1', now() - interval '9 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'd36dbbd9-33b1-4869-8757-71bcfc4d7dfc', 'EKIP_UUID_BURAYA', 'Kuyruk rotoru titreşimi helikopterlerde neredeyse her zaman dengesizlikten kaynaklanır. Kontrol sırası: 1) Kuyruk pervane bıçaklarının ikisinin de ağırlığı aynı mı (bir terazi veya hassas ölçekle tart), farklıysa hafif olan tarafa ince bant ile ağırlık ekle veya bıçakları çift olarak değiştir. 2) Kuyruk mili (tail shaft) eğrilmiş olabilir, düz bir yüzeyde yuvarlayarak eğrilik var mı kontrol et — eğriyse mutlaka değiştir, düzeltmeye çalışma. 3) Kuyruk rulmanları (bearings) aşınmış olabilir, mili elle çevirip sertlik/oynaklık hisset. 4) Kuyruk boom''unu gövdeye bağlayan vidalar gevşemiş olabilir, tork ayarına göre sıkıla.', true, now() - interval '8 days');

-- 15) Helikopter — batarya çok çabuk bitiyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('c8118a37-1e84-4e39-8a9e-dc12fb3d04f5', 'EKIP_UUID_BURAYA', 'Uçuş süresi eskiden 8 dakikaydı, şimdi 3 dakikaya düştü', 'Jenerik', '450 Sınıfı Heli', 'batarya', 'helikopter', 'Aynı bataryayla eskiden 8 dakika uçabiliyordum, son zamanlarda 3 dakikada güç düşüyor ve inmem gerekiyor. Batarya yaklaşık 8 aylık, düzenli kullanıyorum.', 'solved', 'heli-batarya-ucus-suresi-dustu-q0w6r3', now() - interval '7 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'c8118a37-1e84-4e39-8a9e-dc12fb3d04f5', 'EKIP_UUID_BURAYA', '8 aylık düzenli kullanımda kapasite kaybı beklenen bir şey ama %60''a yakın düşüş (8 dk''dan 3 dk''ya) biraz fazla, muhtemelen bataryanın hücrelerinden biri dengesini kaybetmiş (cell imbalance). Bir "balance charger" ile şarj sırasında her hücrenin voltajını ayrı ayrı izle — birbirinden 0.05V''tan fazla sapan bir hücre varsa batarya artık güvenilir değildir. Ayrıca: 1) Bataryayı gözle kontrol et, hafif şişme (puffing) var mı — varsa kullanmayı bırak. 2) İç direnç (internal resistance) ölçebilen bir şarj cihazın varsa ölçtür, yüksek iç direnç kapasite kaybının habercisidir. Genel olarak lipo bataryalar 200-300 şarj döngüsü sonrası performans kaybetmeye başlar, sık kullanıyorsan 8 ayda bu noktaya gelmiş olması mümkün.', true, now() - interval '6 days');

-- 16) RC tekne — gövdeden su kaçırıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('d34af7fb-9000-4534-9fa5-8fbb9daf62dd', 'EKIP_UUID_BURAYA', 'Sudan çıkardıktan sonra gövdenin içinde su birikmiş buluyorum', 'Jenerik', 'RC Sürat Teknesi', 'sasi', 'tekne', 'Her kullanımdan sonra gövdeyi açtığımda içeride biraz su birikmiş oluyor, kaynağını bulamadım. Elektronikler şimdilik zarar görmedi ama endişeliyim.', 'solved', 'rc-tekne-govde-su-kaciriyor-j5t9h2', now() - interval '5 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'd34af7fb-9000-4534-9fa5-8fbb9daf62dd', 'EKIP_UUID_BURAYA', 'RC teknelerde su kaçağının en sık üç noktası: 1) Şaft tüpü (stuffing tube / drive shaft girişi) — pervane şaftının gövdeye girdiği nokta, gres ile doldurulmalı ve o-ring/salmastırası kontrol edilmeli, zamanla aşınır. 2) Dümen (rudder) milinin gövdeye girdiği nokta, aynı şekilde salmastıra/o-ring gerektirir. 3) Gövde kapağının contası (hatch gasket) tam oturmuyor veya yıpranmış olabilir, kapağı kapatmadan önce contanın tam temiz ve düzgün oturduğundan emin ol. Test için: tekneyi suya sokmadan önce gövdeyi kapat, üstüne biraz su dök ve hangi noktadan sızdığını gözlemle, bu kaynağı tam olarak bulmanı sağlar.', true, now() - interval '4 days');

-- 17) RC tekne motoru — suya değince duruyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('3022c5f5-30eb-4db9-988c-173faa38f6ad', 'EKIP_UUID_BURAYA', 'Tekneyi suya koyar koymaz motor duruyor, karada sorunsuz çalışıyor', 'Jenerik', 'RC Sürat Teknesi', 'esc', 'tekne', 'Karada test ederken motor gayet iyi dönüyor ama tekneyi suya koyup gaz verince motor hemen duruyor veya hiç dönmüyor.', 'solved', 'rc-tekne-motor-suda-duruyor-v2y8k4', now() - interval '3 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '3022c5f5-30eb-4db9-988c-173faa38f6ad', 'EKIP_UUID_BURAYA', 'Karada çalışıp suda çalışmaması genelde şu ikisinden biri: 1) ESC''nin "aşırı akım koruması" tetikleniyor — suyun getirdiği ekstra yük (pervanenin suda dönmesi karadakinden çok daha fazla tork ister) motora normalden fazla akım çektiriyor, eğer ESC bu akımı fazla buluyorsa kendini koruma amaçlı kapatıyor. Motor/ESC/pervane kombinasyonunun tekne için uygun olduğundan emin ol (kara test tek başına yeterli değil). 2) Elektronik su alma koruması (waterproof olduğu düşünülen ESC''ye nem kaçmış olabilir), ESC''yi açıp nem/oksidasyon izi var mı kontrol et. Ayrıca gövde içindeki elektronik kutusunun tam su geçirmez kapatıldığından emin ol, tekne elektroniklerinde bu en kritik nokta.', true, now() - interval '2 days');

-- 18) Genel — 2.4GHz alıcı sinyali kesiliyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('8e827704-2197-4221-af49-7c8e43e1418e', 'EKIP_UUID_BURAYA', 'Kumanda ile araç arasında ara ara sinyal kesilmesi (failsafe) yaşıyorum', 'Genel', '2.4GHz Sistemler', 'diger', 'diger', 'Yakın mesafede bile ara sıra sinyal kesilip araç failsafe moduna geçiyor (frenleyip duruyor). Antenler gözle sağlam görünüyor.', 'solved', 'rc-2-4ghz-sinyal-kesiliyor-c1m7b0', now() - interval '1 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '8e827704-2197-4221-af49-7c8e43e1418e', 'EKIP_UUID_BURAYA', '2.4ghz sinyal kesilmeleri genelde şu sebeplerden olur: 1) Alıcı anteninin ucu metal gövde/karbon fiber şasi içine gömülmüşse sinyal ciddi zayıflar, anten ucunun (son 2-3 cm) gövdenin dışında, mümkünse dik açıda durmasını sağla. 2) Aynı ortamda çok sayıda 2.4ghz cihaz (başka kumandalar, wifi router''lar) varsa parazit/çakışma olabilir, kalabalık pist günlerinde bu artar. 3) Kumandanın veya alıcının bataryası/gücü zayıflıyor olabilir, voltajı kontrol et. 4) Bind (eşleştirme) işlemini tekrar yapmak bazen protokol seviyesindeki ufak sorunları çözer. Eğer bunlardan hiçbiri çözmüyorsa alıcı arızalı olabilir, mümkünse başka bir alıcıyla test et.', true, now() - interval '18 hours');
