-- RC Atölyesi — Başlangıç İçeriği, 2. Parti (50 Soru + Çözüm)
-- ============================================================
-- Bu dosya, daha önce gönderilen seed-starter-content.sql (ilk 18 soru)
-- ile AYNI hesabı kullanıyor ve ona EK olarak çalıştırılıyor — birbirini
-- silmiyor, birbirinin üstüne yazmıyor.
--
-- ÇALIŞTIRMADAN ÖNCE:
-- 1) Daha önce açtığın "RC Atölyesi Ekibi" hesabının UUID'ini kullan
--    (ilk dosyada kullandığın ile AYNI UUID olmalı, farklı hesap açma).
-- 2) Aşağıda geçen HER "EKIP_UUID_BURAYA" yazan yeri o UUID ile
--    değiştir (bulundur-değiştir, dosyada çok sayıda yerde geçiyor).
-- 3) Supabase SQL Editor -> New query -> tamamını yapıştır -> Run.
-- ============================================================

-- 1) Traxxas Rustler — ön tekerlek yüksek hızda titriyor (wobble)
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('5d2f1536-9dbe-473b-9b9c-2c2fb5bc13e3', 'EKIP_UUID_BURAYA', 'Yüksek hızda ön tekerlekler sağa sola sallanmaya (wobble) başlıyor', 'Traxxas', 'Rustler', 'sasi', 'araba', 'Belli bir hızın üzerine çıkınca ön tekerlekler kontrolsüzce sağa sola titremeye başlıyor, yavaşlayınca geçiyor. Direksiyon linkajını kontrol ettim gevşek değil.', 'solved', 'traxxas-rustler-on-tekerlek-titriyor-a1', now() - interval '20 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '5d2f1536-9dbe-473b-9b9c-2c2fb5bc13e3', 'EKIP_UUID_BURAYA', 'Bu klasik "yüksek hız titremesi" genelde üç sebepten biri: 1) Ön toe açısı fabrika ayarından kaymış, toe-in''i biraz artırmak hız kararlılığını belirgin iyileştirir. 2) Ön amortisör yağı çok yumuşak, tekerlek yerden hafif kalkıp geri düşerken titreşim başlatıyor, daha sert yağa geç. 3) Tekerlek rulmanları aşınmış olabilir, tekerleği elle çevirip oynaklık var mı kontrol et. Ayrıca batarya çok arkada duruyorsa ön aks hafif kalır, bataryayı biraz öne almak da yardımcı olur.', true, now() - interval '19 days 12 hours');

-- 2) Arrma Notorious — su birikintisinden geçince ESC kapanıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('919cb2f5-7480-4e0f-a416-6e41633accb8', 'EKIP_UUID_BURAYA', 'Su birikintisinden geçince ESC garip bir ses çıkarıp aracı kapatıyor', 'Arrma', 'Notorious', 'esc', 'araba', 'Islak zeminde sürerken bazen ESC''den kısa bir "cırt" sesi geliyor ve araç anında kapanıyor, tekrar açmam gerekiyor. Aracın suya dayanıklı olduğu yazıyordu kutusunda.', 'solved', 'arrma-notorious-esc-su-kapaniyor-b2', now() - interval '19 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '919cb2f5-7480-4e0f-a416-6e41633accb8', 'EKIP_UUID_BURAYA', '"Suya dayanıklı" (water resistant) ile "su geçirmez" (waterproof) arasında ciddi fark var — çoğu hobi sınıfı ESC sadece sıçrama/nem seviyesine dayanıklıdır, göllenmiş suya batmaya değil. O ses muhtemelen kısa devre (arc) sesi; ESC''yi hemen açıp güç kablolarında ve MOSFET''lerde yanık/is izi var mı kontrol et. Eğer ESC''nin altındaki contası/koruma kutusu varsa yerinde mi bak, sık su geçen bir araçsan ESC''yi silikonlu conta ile ekstra izole etmek veya doğrudan waterproof bir ESC''ye yükseltmek en kalıcı çözüm. Islak kullanım sonrası her seferinde açıp kurumaya bırakmak da ömrünü uzatır.', true, now() - interval '18 days 12 hours');

-- 3) HPI Sprint 2 — direksiyon merkezlenmiyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('fec2f367-972b-404e-af41-c62933ae5a12', 'EKIP_UUID_BURAYA', 'Kumandayı bırakınca direksiyon tam ortaya dönmüyor, hep hafif sola kayık kalıyor', 'HPI', 'Sprint 2', 'servo', 'araba', 'Direksiyonu bıraktığımda tekerlekler tam düz gelmiyor, hep birkaç derece sola kayık kalıyor. Kumandada trim ayarını denedim ama kalıcı çözmüyor gibi.', 'solved', 'hpi-sprint2-direksiyon-merkezlenmiyor-c3', now() - interval '18 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'fec2f367-972b-404e-af41-c62933ae5a12', 'EKIP_UUID_BURAYA', 'Kumanda trimi bunu "maskeleyebilir" ama kalıcı çözüm değildir, asıl sorun genelde mekanik: 1) Servo horn''u (kolu) spline dişlerine tam oturmamış olabilir, servoyu merkeze getirip horn''u söküp düzgün açıyla yeniden tak. 2) Direksiyon linkajlarından biri (tie rod) diğerinden farklı uzunlukta ayarlanmış olabilir, iki tarafı da eşit uzunlukta olacak şekilde ayarla. 3) Servo kendisi elektronik olarak merkez kaymışsa (nadir ama olur) servoyu kumandanın kendi "sub-trim" veya "servo center" fonksiyonuyla (varsa) sıfırla, trim ile karıştırma bu farklı bir ayar.', true, now() - interval '17 days 12 hours');

-- 4) Team Associated RC10 — şanzıman sesi çok yüksek
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('33f09a60-4439-4c84-bf61-c109a061d807', 'EKIP_UUID_BURAYA', 'Şanzımandan (gearbox) sürekli yüksek bir uğultu sesi geliyor', 'Team Associated', 'RC10', 'sasi', 'araba', 'Aracı çalıştırdığımda şanzımandan normalden çok daha yüksek, sürekli bir uğultu/vızıltı sesi geliyor. Dişliler gözle kırık görünmüyor.', 'solved', 'associated-rc10-sanziman-sesi-d4', now() - interval '17 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '33f09a60-4439-4c84-bf61-c109a061d807', 'EKIP_UUID_BURAYA', 'Kırık dişli olmasa bile yüksek uğultu genelde dişli boşluğu (mesh/backlash) yanlış ayarlanmış demektir — dişliler ya çok sıkı (birbirine bastırıyor, ses ve ısınma yapar) ya çok gevşek (boşluk sesi yapar) takılmıştır. Pinyon-spur boşluğunu bir kağıt payı bırakacak şekilde yeniden ayarla. Ayrıca şanzıman içindeki gres kurumuş/azalmış olabilir, kapağı açıp dişlilere taze gres sür. Rulmanlardan biri (özellikle spur gear mili) aşınmışsa da benzer bir ses yapar, mili elle çevirip sertlik/oynaklık hisset.', true, now() - interval '16 days 12 hours');

-- 5) Traxxas TRX-4 — crawler tırmanışta gücü kesiliyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('3c1d3eb6-6821-476d-93fa-e28e1b8fd645', 'EKIP_UUID_BURAYA', 'Dik yokuş tırmanırken tam ortasında güç aniden kesiliyor', 'Traxxas', 'TRX-4', 'esc', 'araba', 'Dik ve kayalık bir yokuşu tırmanırken tam yarısında motor aniden duruyor, sanki güç kesiliyor gibi. Düz zeminde hiç sorun yok.', 'solved', 'traxxas-trx4-tirmanista-guc-kesiliyor-e5', now() - interval '16 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '3c1d3eb6-6821-476d-93fa-e28e1b8fd645', 'EKIP_UUID_BURAYA', 'Dik tırmanışta motor ani yük altında çok yüksek akım çeker, bu genelde ESC''nin "aşırı akım/termal koruması" tetiklenmesiyle sonuçlanır — bu bir arıza değil, elektroniği korumak için bilinçli bir güvenlik özelliği. Çözüm için: 1) Daha düşük dişli oranı (gear ratio) kullanarak motora binen yükü azalt, crawler''larda genelde çok yavaş ve yüksek torklu bir kurulum tercih edilir. 2) Tırmanışı tek seferde değil, kademeli gaz vererek dene, ani tam gaz akımı sıçratır. 3) ESC''nin termal koruma eşiği ayarlanabiliyorsa (bazı programlanabilir ESC''lerde var) ve motor/ESC soğutması yeterliyse eşiği biraz yükseltebilirsin, ama motoru da yakmamaya dikkat et.', true, now() - interval '15 days 12 hours');

-- 6) Losi Baja Rey — yağ amortisörleri sızdırıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('6a9ebbc9-6711-4a88-aa02-e8f487e266ce', 'EKIP_UUID_BURAYA', 'Amortisörlerin gövdesinden yağ sızıntısı var, süspansiyon yumuşamış', 'Losi', 'Baja Rey', 'sasi', 'araba', 'İki aydır kullanıyorum, amortisör gövdelerinin etrafında yağlı lekeler oluşmaya başladı ve süspansiyon eskisi kadar sert değil, araç sallanıyor.', 'solved', 'losi-baja-rey-amortisör-sizdiriyor-f6', now() - interval '15 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '6a9ebbc9-6711-4a88-aa02-e8f487e266ce', 'EKIP_UUID_BURAYA', 'Yağ sızıntısı hemen hemen her zaman amortisör keçesinden (o-ring/seal) kaynaklanır — bu keçeler zamanla, özellikle toz/kum girdiğinde aşınır. Onarım evde yapılabilir: amortisörü söküp tamamen boşalt, pistonu ve şaftı temizle, aşınmış o-ring''leri değiştir (yedek keçe setleri ucuza satılıyor), amortisör yağını (genelde 30-40wt arası önerilir, üreticinin önerdiğine bak) hava kabarcığı kalmayacak şekilde tekrar doldur ve kapat. Ayrıca şaftın üstünde çizik/pürüz varsa keçeyi hızlı yıpratır, şaft düzgün görünmüyorsa onu da değiştir.', true, now() - interval '14 days 12 hours');

-- 7) Kyosho Inferno (nitro) — motor ilk çekişte çalışmıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('4b2d750b-d101-4ed9-9870-fb37c2d818b3', 'EKIP_UUID_BURAYA', 'Nitro motor soğukken hiç çalışmıyor, defalarca çekmem gerekiyor', 'Kyosho', 'Inferno', 'motor', 'araba', 'Nitro motorlu arabam soğuk havada ilk çalıştırmada 10-15 çekiş gerektiriyor, motor "gerçekten çalışıyor" gibi hissettirmiyor sadece dönüyor.', 'solved', 'kyosho-inferno-nitro-calismiyor-g7', now() - interval '14 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '4b2d750b-d101-4ed9-9870-fb37c2d818b3', 'EKIP_UUID_BURAYA', 'Nitro motorlarda soğuk çalıştırma zorluğu genelde karbüratör ayarıyla ilgilidir: 1) Karışım vidalarını (needle) üreticinin önerdiği başlangıç ayarına getir, çoğu kişi bunu yanlışlıkla bozar. 2) Glow plug (kızdırma bujisi) zayıflamış olabilir, bujiyi çıkarıp parlak/turuncu kızarıyor mu kontrol et, zayıfsa değiştir — bu en sık gözden kaçan sebep. 3) Yakıt karışımındaki nitro oranı ve yağ oranı motora uygun mu kontrol et, çok eski/bayat yakıt da zor çalışmaya sebep olur. 4) Hava filtresi tıkalı olabilir, temizle. Motoru çalıştırmadan önce birkaç kez "flooding" yapmadan (aşırı yakıt doldurmadan) yavaşça birkaç çekiş yaparak yakıtı sisteme çekmek de yardımcı olur.', true, now() - interval '13 days 12 hours');

-- 8) Redcat Everest — 4WD çekiş asimetrik (bir taraf zayıf)
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a0428c25-fc9d-4707-9f01-70a8b54cfb8f', 'EKIP_UUID_BURAYA', 'Sağ ön teker diğerlerinden daha az güç alıyor gibi, düz gitmiyor', 'Redcat', 'Everest', 'sasi', 'araba', '4WD olmasına rağmen sağ ön tekerlek diğer üçüne göre daha yavaş/zayıf dönüyor gibi görünüyor, araç hafif sağa çekiyor engebeli zeminde.', 'solved', 'redcat-everest-cekis-asimetrik-h8', now() - interval '13 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a0428c25-fc9d-4707-9f01-70a8b54cfb8f', 'EKIP_UUID_BURAYA', 'Bir tekerleğin diğerlerinden zayıf kalması genelde şu zincirdeki bir noktada tıkanma anlamına gelir: 1) O tekerleğe giden CV mili (aks) tam oturmamış veya hafif eğri olabilir, sökülüp kontrol et. 2) Diferansiyel içindeki dişlilerden biri o tekerleğe giden tarafta sıkışmış/aşınmış olabilir. 3) Wheel hub (jant göbeği) ile aks arasındaki bağlantı gevşemiş olabilir, kayma yapıyor olabilir. En hızlı teşhis yöntemi: aracı kaldırıp her tekerleği tek tek elle çevirerek dirençleri karşılaştırmak, hangi noktada anormal sertlik/boşluk olduğunu bulman sorunu doğrudan gösterir.', true, now() - interval '12 days 12 hours');

-- 9) Arrma Granite — fırçalı motor kıvılcım çıkarıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('8a84310b-5b23-4701-b4fd-0094113725b8', 'EKIP_UUID_BURAYA', 'Motor içinden gaz verince kıvılcım/parıltı görünüyor, koku da var', 'Arrma', 'Granite', 'motor', 'araba', 'Fırçalı motorlu bir araç, gaz verince motorun havalandırma deliklerinden ufak kıvılcımlar görüyorum ve hafif yanık kokusu var. Motor eski sayılır.', 'solved', 'arrma-granite-motor-kivilcim-i9', now() - interval '12 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '8a84310b-5b23-4701-b4fd-0094113725b8', 'EKIP_UUID_BURAYA', 'Fırçalı motorlarda hafif kıvılcım aslında fırça-komütatör temasının doğal bir parçasıdır ve normal koşulda çok az/görünmez olur, ama belirgin kıvılcım + yanık kokusu genelde fırçaların aşınıp ömrünü tamamladığının işaretidir. Motoru sökebiliyorsan (bazı fırçalı motorlarda kapak sökülebilir) fırçaların uzunluğunu kontrol et, kısalmışsa değiştir. Komütatör yüzeyi de kararmış/pürüzlü olabilir, ince zımpara kağıdıyla nazikçe temizlenebilir. Eğer motor sökülemeyen kapalı tip ise ve semptomlar kötüleşiyorsa artık motoru değiştirmenin zamanı gelmiş demektir, fırçalı motorlar sarf malzemesi kabul edilir.', true, now() - interval '11 days 12 hours');

-- 10) HSP 94188 — alıcı anteni koptu
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('92e85b1b-51ae-4f3b-ab74-14f5c451ae0c', 'EKIP_UUID_BURAYA', 'Bir kazada alıcının anten kablosu koptu, değiştirmem mi lazım?', 'HSP', '94188', 'diger', 'araba', 'Küçük bir kazada alıcı ünitesinin anten teli tam dibinden koptu. Araç hâlâ sinyal alıyor ama menzil çok kısaldı.', 'solved', 'hsp-94188-anten-koptu-j0', now() - interval '11 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '92e85b1b-51ae-4f3b-ab74-14f5c451ae0c', 'EKIP_UUID_BURAYA', 'Anten teli menzil için kritik, koptuğunda sinyalin hâlâ (kısıtlı) gelmesi normal ama menzilin ciddi düşmesi beklenen bir sonuç, kazayla devam etmemelisin çünkü menzil dışına çıkınca kontrolü tamamen kaybedebilirsin. Çözüm: aynı uzunlukta (genelde 2.4ghz alıcılarda birkaç cm''lik kısa bir tel/parça) ince bir kablo lehimle antenin köküne eklemek mümkün ama hassas bir iş, lehim tekniğin yoksa alıcıyı değiştirmek daha güvenli. Ucuz 2.4ghz alıcılar zaten düşük maliyetli olduğu için, garanti/orijinal parça bulamıyorsan uyumlu bir yedek alıcı almak genelde en pratik çözüm.', true, now() - interval '10 days 12 hours');

-- 11) WLtoys 12428 — diferansiyel plastik dişliler kırılıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('59da3bfe-caf8-4795-8226-39dba2833cca', 'EKIP_UUID_BURAYA', 'Diferansiyel dişlileri sürekli kırılıyor, üçüncü kez değiştiriyorum', 'WLtoys', '12428', 'sasi', 'araba', 'Plastik diferansiyel dişlileri kısa aralıklarla kırılıyor. Agresif sürmüyorum, düz zeminlerde de kırılıyor bazen.', 'solved', 'wltoys-12428-difransiyel-kiriliyor-k1', now() - interval '10 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '59da3bfe-caf8-4795-8226-39dba2833cca', 'EKIP_UUID_BURAYA', 'Bütçe RC araçlarda plastik diferansiyel dişlisi genelde zayıf halkadır, özellikle motoru daha güçlü bir sürüme (upgrade motor/ESC) değiştirdiysen dişliler orijinal tasarlanan güçten fazlasını taşımaya çalışıyor demektir ve kırılmaya devam eder. En kalıcı çözüm: metal (çelik) diferansiyel dişli setine yükseltmek, bu modellerde genelde uygun fiyatlı metal upgrade setleri satılıyor. Motoru upgrade etmediysen bile, ani ve tam gaz kalkışlar (özellikle engebede) dişliye ani darbe yükü bindirir, kademeli gaz vermek dişli ömrünü uzatır.', true, now() - interval '9 days 12 hours');

-- 12) Traxxas Stampede — şarj cihazı bataryayı tanımıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('59eaf6a3-df4e-47de-93f0-9c192be66880', 'EKIP_UUID_BURAYA', 'Şarj cihazı bataryayı taktığımda "no battery" / bağlantı yok yazıyor', 'Traxxas', 'Stampede', 'batarya', 'araba', 'iD bağlantılı Traxxas şarj cihazım, bataryayı takınca ekranda batarya algılanmadığını gösteriyor. Konnektör temiz görünüyor.', 'solved', 'traxxas-sarj-batarya-taninmiyor-l2', now() - interval '9 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '59eaf6a3-df4e-47de-93f0-9c192be66880', 'EKIP_UUID_BURAYA', 'Traxxas iD sistemi, konnektörün içindeki küçük bir ID pini/çipi üzerinden bataryayı tanır, sadece güç bağlantısı yeterli değildir. Kontrol sırası: 1) Konnektörü tamamen tam oturana kadar (klik sesi) itip taktığından emin ol, yarım oturma çok sık yaşanır. 2) Konnektör pinlerinde oksidasyon/kararma varsa hafifçe temizle. 3) Batarya gerçekten çok derin deşarj olmuşsa (aşırı boşalmış) bazı iD şarj cihazları güvenlik amaçlı tanımayı reddedebilir. 4) Şansını denemek için farklı bir bataryayla aynı şarj cihazını test et, sorun şarj cihazında mı bataryada mı ayırt edersin.', true, now() - interval '8 days 12 hours');

-- 13) Arrma Talion — servo saver gevşedi
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('6d124067-f425-407d-98e3-1e6f01bd33b5', 'EKIP_UUID_BURAYA', 'Direksiyon sisteminde oynaklık var, servo saver gevşek gibi', 'Arrma', 'Talion', 'servo', 'araba', 'Direksiyon linkajında elle hissedilir bir oynaklık var, tekerlekleri elle hafifçe sallayabiliyorum. Servo saver yayının civatası gevşemiş olabilir mi?', 'solved', 'arrma-talion-servo-saver-gevsek-m3', now() - interval '8 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '6d124067-f425-407d-98e3-1e6f01bd33b5', 'EKIP_UUID_BURAYA', 'Kesinlikle mümkün ve en sık rastlanan sebeplerden biri — servo saver''ın merkez somunu (kilit somunu) zamanla titreşimle gevşeyebilir. Somunu sıkarken servo saver yayının hâlâ hafifçe hareket edebildiğinden (tamamen kilitlemeden) emin ol, çünkü bu yay çarpma anında servoyu koruyan güvenlik parçası, tamamen katılaştırırsan darbe anında servo dişlileri zarar görebilir. Somunu sıktıktan sonra dişli sabitleyici (Loctite mavi) sürmek tekrar gevşemesini engeller. Oynaklık hâlâ devam ediyorsa servo saver''ın içindeki pivot pimi veya plastik gövde aşınmış/kırık olabilir, görsel olarak kontrol et.', true, now() - interval '7 days 12 hours');

-- 14) HPI E10 — fırçasız motor konnektörü erimiş
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('4a1a43e4-ac8f-42d1-9c09-1bfe09268eb4', 'EKIP_UUID_BURAYA', 'Motor konnektörlerinden biri erimiş/deforme olmuş buldum', 'HPI', 'E10', 'motor', 'araba', 'Uzun bir sürüşten sonra motor-ESC bağlantı konnektörlerinden birinin plastik gövdesi erimiş/eğrilmiş halde buldum. Araç sırasında hiç anormal davranmadı.', 'solved', 'hpi-e10-konnektor-erimis-n4', now() - interval '7 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '4a1a43e4-ac8f-42d1-9c09-1bfe09268eb4', 'EKIP_UUID_BURAYA', 'Konnektör erimesi doğrudan aşırı ısınmanın (ve genelde de kötü/gevşek bir bağlantının) belirtisidir — konnektör pinleri tam oturmazsa temas direnci artar, bu da o noktada aşırı ısı üretir (elektriksel direnç kaybı ısıya dönüşür). Bu ciddi bir güvenlik riski, yangın tehlikesi oluşturabilir. Yapman gerekenler: 1) O konnektörü kesinlikle yenisiyle değiştir, eriyen konnektörü tekrar kullanma. 2) Yeni konnektör lehimlerken kabloların tam ve sağlam lehimlendiğinden emin ol, gevşek lehim bağlantısı aynı sorunu tekrarlar. 3) Motorun çektiği akıma uygun kalınlıkta (amper kapasiteli) konnektör kullandığından emin ol, motor/ESC gücüne göre çok ince konnektör kullanmak da ısınmaya sebep olur.', true, now() - interval '6 days 12 hours');

-- 15) Losi Tenacity — lastik janttan çıkıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('85c0a51f-a316-41c3-a539-a2cc4e6793d8', 'EKIP_UUID_BURAYA', 'Sert dönüşlerde lastik jantın üzerinden kayıp çıkıyor', 'Losi', 'Tenacity', 'lastik', 'araba', 'Sert virajlarda bazen lastik janttan tamamen ayrılıp çıkıyor. Lastikleri yapıştırmamıştım, sadece geçirilmiş şekilde takılıydı.', 'solved', 'losi-tenacity-lastik-janttan-cikiyor-o5', now() - interval '6 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '85c0a51f-a316-41c3-a539-a2cc4e6793d8', 'EKIP_UUID_BURAYA', 'Lastiklerin yapıştırılmadan sadece geçirilmiş olması tam olarak bu sorunun sebebi — yandal (lateral) kuvvetler altında (viraj, çarpma) lastik jant üzerinde kayar ve tamamen çıkabilir. Çözüm çok basit ama ihmal edilen bir adım: lastikleri jantlara RC''ye özel lastik yapıştırıcısı (CA/siyanoakrilat bazlı, hızlı kuruyan tip) ile yapıştırmak. Jant kenarını ve lastik iç kısmını önce temizle (toz/yağ olmasın), yapıştırıcıyı jant çevresine ince ve eşit sür, lastiği yerleştirip birkaç dakika sabit tut, tam kürlenmesi için birkaç saat bekle. Bu işlem yapıldıktan sonra bu sorun neredeyse hiç yaşanmaz.', true, now() - interval '5 days 12 hours');

-- 16) Traxxas XO-1 — üst hızda titreme
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('2e634e29-330f-40fe-b71b-2e7771d0628f', 'EKIP_UUID_BURAYA', 'Üst hıza yakın giderken araç şiddetli titremeye başlıyor', 'Traxxas', 'XO-1', 'sasi', 'araba', 'Aracımın üst hızına (100+ km/s civarı) yaklaşırken şiddetli bir titreşim başlıyor, kontrolü zorlaştırıyor. Düşük-orta hızlarda sorun yok.', 'solved', 'traxxas-xo1-ust-hiz-titreme-p6', now() - interval '5 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '2e634e29-330f-40fe-b71b-2e7771d0628f', 'EKIP_UUID_BURAYA', 'Yüksek hız RC araçlarında bu klasik bir sorun ve genelde tekerlek/lastik dengesinden kaynaklanır — normal hızlarda fark edilmeyen çok küçük bir dengesizlik, üst hızda RPM arttıkça şiddetlenir (tıpkı araba lastiği balanssızlığı gibi). Kontrol listesi: 1) Her tekerleği pervane dengeleyici mantığıyla (bir eksende serbestçe döndürüp ağır tarafı bulmak) dengele. 2) Lastik yapıştırması düzgün ve simetrik mi kontrol et, eğri yapıştırılmış lastik dengesizlik yaratır. 3) Aks ve rulmanlarda eğrilik/oynaklık olmadığından emin ol. 4) Şasi ve gövde vidalarının tam sıkı olduğunu doğrula, üst hızda gevşek bir parça titreşimi büyük ölçüde artırabilir.', true, now() - interval '4 days 12 hours');

-- 17) FTX Carnage — ESC sık sık ısınıp kapanıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('8f3a4fe0-c2e4-42ab-be52-26f1cf7fb6b1', 'EKIP_UUID_BURAYA', 'ESC 5-6 dakika sonra ısınıp kendini kapatıyor, soğuyunca tekrar açılıyor', 'FTX', 'Carnage', 'esc', 'araba', 'Sürekli sürüşte ESC yaklaşık 5-6 dakika sonra kapanıyor, birkaç dakika bekleyip soğutunca tekrar çalışıyor. Havalandırması açık görünüyor.', 'solved', 'ftx-carnage-esc-isiniyor-q7', now() - interval '4 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '8f3a4fe0-c2e4-42ab-be52-26f1cf7fb6b1', 'EKIP_UUID_BURAYA', 'Bu davranış tam olarak termal koruma devresinin tetiklenmesi — ESC belirli bir sıcaklığa ulaşınca kendini korumak için kapanıyor, soğuyunca tekrar çalışması bunu doğruluyor (arızalı olsa tekrar açılmazdı). Sebepleri: 1) Motor/ESC kombinasyonu birbirine göre yetersiz (çok agresif bir motora karşı zayıf bir ESC), sürekli yüksek akım çekiyor. 2) ESC''nin fanı varsa çalışmıyor olabilir, fan bağlantısını ve dönüp dönmediğini kontrol et. 3) ESC gövdesi kapalı bir alana monte edilmişse hava akışı yetersiz kalır, mümkünse daha açık havalandırmalı bir konuma taşı veya ekstra bir fan/ısı emici (heatsink) ekle. Geçici çözüm olarak arada mola vermek yerine kalıcı olarak soğutmayı iyileştirmek gerekir.', true, now() - interval '3 days 12 hours');

-- 18) Team Losi Mini-T — pinyon aşırı ısınıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('7ae1c1ae-b2c9-4e2e-9da8-224074377c4a', 'EKIP_UUID_BURAYA', 'Küçük ölçekli aracımda pinyon dişlisi kısa sürede çok ısınıyor', 'Team Losi', 'Mini-T', 'motor', 'araba', 'Mini ölçekli aracımda pinyon dişlisi birkaç dakikada dokunulmayacak kadar ısınıyor, motor gövdesi ise nispeten serin kalıyor.', 'solved', 'losi-minit-pinyon-isiniyor-r8', now() - interval '3 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '7ae1c1ae-b2c9-4e2e-9da8-224074377c4a', 'EKIP_UUID_BURAYA', 'Isının motordan çok pinyon/spur bölgesinde toplanması, mekanik sürtünmeye işaret eder — motor kendisi sorunlu değil demektir. Pinyon-spur dişli boşluğunu (mesh) kontrol et: çok sıkı takılmışsa dişliler birbirine bastırır, sürekli sürtünme ısı üretir. Bir kağıt kalınlığı kadar boşluk bırakacak şekilde motor mount''unu gevşetip yeniden ayarla. Ayrıca küçük ölçekli araçlarda pinyon vida/set vidası tam sıkı değilse mil üzerinde mikro kayma yapıp ısı üretebilir, set vidasının tam sıkı olduğunu ve motor miline düz bir yüzeyde oturduğunu kontrol et.', true, now() - interval '2 days 12 hours');

-- 19) Redcat Blackout — diferansiyel kilitleri tutmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a92f1b67-affe-40ab-83b4-9e0e09209406', 'EKIP_UUID_BURAYA', '4x4 crawler''da diferansiyel kilidi açık olsa bile bir teker boşta dönüyor', 'Redcat', 'Blackout XTE', 'sasi', 'araba', 'Zorlu arazide diferansiyel kilidini devreye alsam bile bir tekerlek yerde havada kaldığında boşta dönmeye devam ediyor, kilit çalışmıyor gibi.', 'solved', 'redcat-blackout-difransiyel-kilit-s9', now() - interval '2 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a92f1b67-affe-40ab-83b4-9e0e09209406', 'EKIP_UUID_BURAYA', 'Önce şunu netleştirelim: bu modelin standart diferansiyeli gerçek "kilitli diferansiyel" değilse (birçok hobi sınıfı crawler''da sadece açık diferansiyel bulunur, "locker" ayrı bir upgrade parçasıdır), o zaman bu beklenen bir davranıştır — açık diferansiyel her zaman en az dirençli tekerleğe gücü yönlendirir, havadaki teker dönmeye devam eder. Eğer aracında gerçek bir kilitli/locker diferansiyel varsa ve çalışmıyorsa: kilit mekanizmasını tetikleyen servo veya manuel mekanizmanın tam devreye girip girmediğini kontrol et, çoğu zaman kilitleme pimi tam oturmuyor. Gerçek kilit yoksa, çözüm bir "locker" veya kilitli diferansiyel upgrade parçası satın almaktır.', true, now() - interval '1 days 12 hours');

-- 20) Arrma Infraction — drift lastikleri erken kayganlaşıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('dd52df1f-8269-4da1-bc79-56cf6bcf8c86', 'EKIP_UUID_BURAYA', 'Drift lastikleri birkaç koşuda camsı/kaygan bir yüzeye dönüşüyor', 'Arrma', 'Infraction', 'lastik', 'araba', 'Drift için kullandığım lastikler birkaç koşu sonra yüzeyleri camsı, parlak ve normalden daha kaygan hale geliyor, tutuş azalıyor.', 'solved', 'arrma-infraction-lastik-camsi-t0', now() - interval '1 days');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'dd52df1f-8269-4da1-bc79-56cf6bcf8c86', 'EKIP_UUID_BURAYA', 'Drift lastiklerinde bu aslında istenen/beklenen bir durum — drift lastikleri kasıtlı olarak sert bileşimden yapılır ve kayma sırasında yüzeyleri ısı+sürtünmeyle camlaşır (bu "glazing" olarak bilinir), bu da drift''in karakteristik kontrollü kaymasını sağlayan şeydir, normal grip lastiği gibi tutunmaları beklenmez. Eğer aşırı kaygan bulduysan: 1) Silikon sprey ile lastik yüzeyini işlemek (bazı drift''çiler bunu tercih ediyor) kaymayı daha kontrol edilebilir hale getirebilir. 2) Farklı sertlikte (daha az sert) bir drift lastiği bileşimi deneyebilirsin, üreticiler genelde birkaç sertlik seçeneği sunar. 3) Eğer aslında normal grip (tutunma) istiyorsan, drift lastiği yerine standart on-road/touring lastiği kullanman gerekiyor, farklı amaçlar için tasarlanmışlar.', true, now() - interval '20 hours');

-- 21) Traxxas Bandit — kumanda menzili kısa
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('11938cf3-399b-4e7e-952a-aa9c0475f378', 'EKIP_UUID_BURAYA', 'Kumanda menzili çok kısa, 20-30 metreden sonra sinyal kesiliyor', 'Traxxas', 'Bandit', 'diger', 'araba', '2.4ghz kumandam açık alanda bile 20-30 metreden sonra sinyal kaybediyor, araç failsafe''e giriyor. Eskiden çok daha uzun mesafede sorunsuzdu.', 'solved', 'traxxas-bandit-menzil-kisa-u1', now() - interval '20 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '11938cf3-399b-4e7e-952a-aa9c0475f378', 'EKIP_UUID_BURAYA', '"Eskiden çok daha uzundu" ifaden önemli bir ipucu, yani sistemin kendisi zamanla kötüleşmiş. En sık sebepler: 1) Kumandanın pilleri zayıflamış, düşük pil voltajı verici gücünü azaltır, pilleri değiştir/şarj et. 2) Alıcı anteni gövde içinde bir yere sıkışmış veya metal parçaya çok yakın kalmış olabilir, konumunu kontrol et. 3) Kumanda anteni tam açık ve dik değilse (bazı kumandalarda katlanabilir anten var) sinyal zayıflar. 4) Yakında sinyal karıştıran başka bir 2.4ghz cihaz (yoğun wifi bölgesi, başka kumandalar) olabilir. Bu dördü de normalse, alıcı veya vericinin kendisinde bir donanım arızası olabilir, mümkünse başka bir kumanda/alıcı çiftiyle test et.', true, now() - interval '19 hours');

-- 22) HPI Baja 5B (benzinli) — rölantide duruyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('42ba7ada-7d98-4632-a5d8-21ae655057ad', 'EKIP_UUID_BURAYA', 'Benzin motor rölantide birkaç saniye sonra kendiliğinden duruyor', 'HPI', 'Baja 5B', 'motor', 'araba', 'Benzinli motorum çalışıyor ama rölantide bırakınca 5-10 saniye içinde kendiliğinden duruyor, gaz verirsem sorun yok.', 'solved', 'hpi-baja5b-rolantide-duruyor-v2', now() - interval '19 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '42ba7ada-7d98-4632-a5d8-21ae655057ad', 'EKIP_UUID_BURAYA', 'Rölantide durup gazla çalışmaya devam etmesi, karbüratörün rölanti (idle) ayarının çok düşük veya karışımının uygunsuz olduğuna işaret eder. Sırayla dene: 1) Rölanti vidasını (idle screw) hafifçe sıkarak (RPM''i biraz artırarak) motorun düşük devirde de sönmeden çalışacağı noktayı bul. 2) Karışım ayarının (özellikle düşük hız/idle needle) çok fakir (az yakıt) olup olmadığını kontrol et, biraz zenginleştir. 3) Hava filtresi kirli/tıkalıysa düşük devirde yeterli hava alamayıp sönebilir, temizle. 4) Kumanda trimindeki karbüratör kapanma pozisyonu, karbüratörü tam kapatıyor olabilir (rölantiyi sıfıra indiriyor), throttle trim/endpoint ayarlarını kontrol et.', true, now() - interval '18 hours');

-- 23) Losi DBXL — ön süspansiyon çökmüş
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('bc39bb40-64b1-4108-af22-e15ea75be67a', 'EKIP_UUID_BURAYA', 'Ön süspansiyon zamanla çökmüş, araç öne doğru eğik duruyor', 'Losi', 'DBXL', 'sasi', 'araba', 'Araç dururken bile ön kısım arkaya göre daha aşağıda duruyor, sanki ön süspansiyon zamanla çökmüş gibi. Aktif kullanıyorum, sık atlıyor.', 'solved', 'losi-dbxl-on-suspansiyon-cokmus-w3', now() - interval '18 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'bc39bb40-64b1-4108-af22-e15ea75be67a', 'EKIP_UUID_BURAYA', 'Sık atlama/iniş yapan bir kullanım tarzında bu genelde amortisör yayının (spring) zamanla esnekliğini kaybetmesinden veya amortisör yağının incelmesinden (sürekli ısınıp soğuma yağın viskozitesini bozabilir) kaynaklanır. Kontrol sırası: 1) Yayları sökülüp gözle karşılaştır, sıkışmış/kalıcı deforme olmuş görünüyorsa değiştir. 2) Amortisör yağını boşaltıp taze, üreticinin önerdiği viskozitede yağ ile değiştir. 3) Sık sert iniş yapıyorsan daha sert (yüksek numaralı) yay/yağ kombinasyonuna geçmeyi düşün, mevcut kurulum senin kullanım tarzın için fazla yumuşak kalmış olabilir.', true, now() - interval '17 hours');

-- 24) Arrma Outcast — LiPo konnektörü aşırı ısınıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('508ad879-4b5a-4afe-aad7-e91ec6454ee1', 'EKIP_UUID_BURAYA', 'Batarya konnektörü sürüş sonrası elle dokunulamayacak kadar sıcak oluyor', 'Arrma', 'Outcast', 'batarya', 'araba', 'Sürüş bitince batarya konnektörünü (XT90) çıkarmaya çalışırken elimi yakacak kadar sıcak olduğunu fark ettim. Batarya kendisi bu kadar sıcak değil.', 'solved', 'arrma-outcast-konnektor-isiniyor-x4', now() - interval '17 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '508ad879-4b5a-4afe-aad7-e91ec6454ee1', 'EKIP_UUID_BURAYA', 'Bataryanın kendisi sıcak değilken konnektörün aşırı ısınması, konnektör noktasında yüksek elektriksel direnç olduğunu gösterir — bu genelde gevşek/tam oturmamış bir bağlantı veya lehim kalitesinden kaynaklanır, GÜVENLİK AÇISINDAN CİDDİYE ALINMALI çünkü yangın riski taşır. Kontrol et: 1) Konnektör pinleri kararmış/oksitlenmiş mi, temizle veya değiştir. 2) Konnektörün lehim noktalarında kötü/az lehim var mı, varsa yeniden lehimle. 3) Bu araç için konnektör amper kapasitesi yeterli mi (XT90 genelde yüksek akım için uygundur ama sahte/düşük kaliteli kopyalar sorun çıkarabilir), orijinal/kaliteli marka konnektör kullan. Bu sorunu görmezden gelmemeni öneririz.', true, now() - interval '16 hours');

-- 25) Redcat Camo X4 — throttle trim merkezde tutmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('114ec1c3-c824-4aba-aa82-552d0393d667', 'EKIP_UUID_BURAYA', 'Gaz kolunu bırakınca tam nötre gelmiyor, araç hafif ileri sürünmeye devam ediyor', 'Redcat', 'Camo X4', 'servo', 'araba', 'Kumandanın gaz kolunu bıraktığımda araç durması gerekirken hafifçe ileri doğru sürünmeye devam ediyor, sanki gaz tam kapanmıyor.', 'solved', 'redcat-camox4-throttle-merkezde-degil-y5', now() - interval '16 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '114ec1c3-c824-4aba-aa82-552d0393d667', 'EKIP_UUID_BURAYA', 'Bu, kumandanın gaz kolu nötr sinyalinin ESC''nin beklediği nötr noktasından kaymış olduğu anlamına geliyor. İki adımda çöz: 1) Kumandanın throttle trim düğmesiyle nötr noktasını manuel ayarlamayı dene, gaz kolu tam ortadayken araç tam dursun. 2) Trim yeterli gelmiyorsa veya sürekli kayıyorsa, ESC''yi yeniden kalibre et (genelde açma düğmesine basılı tutup gaz kolunu sırasıyla tam ileri-tam geri-nötre getirerek yapılır), bu ESC''ye "gerçek nötr" konumunu yeniden öğretir ve trim ayarını sıfırdan doğru kurar.', true, now() - interval '15 hours');

-- 26) DJI benzeri mini drone — piller şişmiş
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('3cc11d3b-2f51-4ab5-a297-f768897cfa8a', 'EKIP_UUID_BURAYA', 'Batarya gözle görülür şekilde şişmiş, kullanmaya devam edebilir miyim?', 'DJI', 'Mini benzeri (jenerik)', 'batarya', 'drone', 'Dronemun bataryasını gövdeden çıkarınca hafif şişmiş olduğunu fark ettim, düz durmuyor artık. Uçuş performansı da düşmüştü son zamanlarda.', 'solved', 'drone-batarya-sismis-z6', now() - interval '15 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '3cc11d3b-2f51-4ab5-a297-f768897cfa8a', 'EKIP_UUID_BURAYA', 'ÖNEMLİ GÜVENLİK UYARISI: Şişmiş bir lipo bataryayı KESİNLİKLE kullanmaya, şarj etmeye veya uçuşa çıkarmaya devam etme. Şişme, hücre içindeki kimyasal yapının bozulduğunu gösterir ve bu batarya artık yangın/patlama riski taşır, özellikle şarj sırasında. Yapman gerekenler: 1) Bataryayı yanıcı olmayan bir zeminde (metal kutu, seramik) ve yanıcı maddelerden uzakta sakla, uçuşa çıkarma. 2) İmha için: bataryayı birkaç gün tuzlu suda (yaklaşık %5 tuz oranı) tamamen batmış halde bekletmek, tam deşarj olup güvenli hale gelmesini sağlar (yerel elektronik/pil atık noktalarına götürmeden önce bu yaygın bir güvenli imha yöntemidir). Performans düşüşünün şişmeden önce başlaması da normal, hücre bozulması genelde performans kaybıyla önceden kendini belli eder.', true, now() - interval '14 hours');

-- 27) FPV drone — VTX görüntü kesiliyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('2a5c7c04-c712-4071-bb92-8616550cc0b8', 'EKIP_UUID_BURAYA', 'Belirli bir mesafeden sonra FPV görüntüsü kesik kesik geliyor', 'Jenerik', 'FPV Racing Drone', 'diger', 'drone', 'Yaklaşık 150-200 metreden sonra gözlükteki (goggle) görüntü kesik kesik/parazitli gelmeye başlıyor, drone kontrolü hâlâ çalışıyor ama görüntü kötü.', 'solved', 'fpv-drone-vtx-goruntu-kesiliyor-a7', now() - interval '14 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '2a5c7c04-c712-4071-bb92-8616550cc0b8', 'EKIP_UUID_BURAYA', 'Video sinyali (VTX/analog veya dijital) ile kontrol sinyali (RC link) farklı frekans/güç sistemleri kullanır, bu yüzden kontrol çalışırken görüntünün bozulması mantıklı — video linkinin menzili genelde kontrol linkinden daha kısadır. Kontrol et: 1) VTX gücünü (varsa ayarlanabilir mW seviyesi) artırabiliyor musun, çoğu VTX 25mW-200mW-600mW gibi kademeler sunar, mesafe için daha yüksek güç gerekir (yerel frekans/güç düzenlemelerine dikkat ederek). 2) VTX ve gözlük antenlerinin polarizasyonu (RHCP/LHCP) eşleşiyor mu kontrol et, uyumsuz polarizasyon sinyali zayıflatır. 3) Gözlükteki anten yönlü (patch) bir anten ise ve drone belirli bir açının dışına çıkıyorsa sinyal kesilebilir, omnidirectional antene geçmeyi düşün. 4) Ortamda VTX ile aynı frekans bandında yayın yapan başka cihazlar (kamera, wifi) parazit yaratıyor olabilir.', true, now() - interval '13 hours');

-- 28) Racing drone — flight controller kalibrasyonu bozuluyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('437db518-b46e-48d2-aa9f-d2d11cfa0391', 'EKIP_UUID_BURAYA', 'Her açılışta jiroskop kalibrasyonu bozuluyor, drone tek tarafa yatıyor', 'Jenerik', 'FPV Racing Drone', 'diger', 'drone', 'Her açılışta drone havada dururken bir tarafa doğru yatma eğiliminde, sanki jiroskop kalibrasyonu kayıyor. Yazılımdan kalibre etsem de bir süre sonra tekrar bozuluyor.', 'solved', 'fpv-drone-gyro-kalibrasyon-bozuluyor-b8', now() - interval '13 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '437db518-b46e-48d2-aa9f-d2d11cfa0391', 'EKIP_UUID_BURAYA', 'Kalibrasyonun "tutmaması" (kalıcı olmaması) genelde iki şeyden biri: 1) Flight controller (uçuş kontrolcüsü) gövdeye tam sabit monte edilmemiş, hafif titreşim/oynama sensörleri şaşırtır — montaj vidalarının tam sıkı olduğundan ve titreşim emici pedlerin (varsa) sağlam olduğundan emin ol. 2) Kalibrasyon sırasında drone tam düz ve sabit bir zeminde durmuyor olabilir, kalibrasyonu mutlaka tam yatay, sabit bir yüzeyde yap. 3) Flight controller''ın kendi sensöründe (gyro/accelerometer) bir donanım problemi olabilir, özellikle drone daha önce sert bir çarpma yaşadıysa. Yazılım tarafında (Betaflight vb. kullanıyorsan) "accelerometer trim" ayarını da kontrol edip ince ayar yapman gerekebilir.', true, now() - interval '12 hours');

-- 29) Kamera drone — gimbal kalkışta yamuk duruyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('b80caf2f-3f47-4784-822b-a87db2432ed2', 'EKIP_UUID_BURAYA', 'Kalkışta kamera gimbal''ı yamuk açıda kalıyor, otomatik düzelmiyor', 'Jenerik', 'Kamera Drone', 'diger', 'drone', 'Drone kalkarken kamera gimbal''ı yatay durması gerekirken hafif eğik/yamuk kalıyor, birkaç saniye sonra kendiliğinden düzeliyor ama can sıkıcı.', 'solved', 'drone-gimbal-yamuk-c9', now() - interval '12 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'b80caf2f-3f47-4784-822b-a87db2432ed2', 'EKIP_UUID_BURAYA', 'Bu genelde gimbal''ın başlangıç kalibrasyon/kendini bulma (auto-level) sürecinin kalkışla çakışmasından kaynaklanır — gimbal motorları açılışta kısa bir "self-check" yapar ve bu sırada geçici olarak yamuk durabilir, birkaç saniyede kendini düzeltmesi aslında normaldir. Eğer bu süre çok uzuyorsa veya düzelmiyor gibi görünüyorsa: 1) Uçuş öncesi drone''u açtıktan sonra kalkmadan önce en az 5-10 saniye bekle, gimbal''ın kendini toparlamasına izin ver. 2) Gimbal''ın kendi kalibrasyon fonksiyonunu (varsa uygulama üzerinden) çalıştır. 3) Gimbal montaj vidaları gevşemiş olabilir, sabitliğini kontrol et. 4) Gimbal ribbon kablosu (ince bağlantı kablosu) hasarlıysa da tuhaf hareketler görülebilir, görsel kontrol et.', true, now() - interval '11 hours');

-- 30) Toy-grade drone — her inişte pervane kırılıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('6089b3a6-9044-4950-bc22-278af78f5854', 'EKIP_UUID_BURAYA', 'Ufak bir çarpma veya inişte pervaneler çok kolay kırılıyor', 'Jenerik', 'Başlangıç Seviyesi Mini Drone', 'diger', 'drone', 'Yeni başladığım için sık düşürüyorum ama pervaneler neredeyse her ufak temaste kırılıyor, sürekli yedek almam gerekiyor.', 'solved', 'drone-pervane-kolay-kiriliyor-d0', now() - interval '11 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '6089b3a6-9044-4950-bc22-278af78f5854', 'EKIP_UUID_BURAYA', 'Başlangıç seviyesindeyken bu tamamen normal, herkes bu aşamadan geçer — ama birkaç şey pervane ömrünü uzatabilir: 1) Sert plastik yerine esnek/kompozit malzemeli pervanelere geçmeyi düşün, çarpmada kırılmak yerine bükülüp geri dönerler. 2) Eğer drone''unda pervane koruyucu (prop guard) takılabiliyorsa mutlaka tak, özellikle öğrenme aşamasında kırılmaları ciddi azaltır. 3) Uçuş modunu (varsa) "beginner/acil frenleme" moduna al, bu modlar çarpma riskini azaltan otomatik dengeleme sunar. 4) Toplu paket halinde yedek pervane almak (genelde ucuza satılıyor) maliyeti pratikleştirir, bunu bir "sarf malzeme" olarak düşün, çekinme.', true, now() - interval '10 hours');

-- 31) FPV drone — ESC senkronizasyon hatası, motor tutuşmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('70e84aab-daef-4286-aa69-0ce069e6892a', 'EKIP_UUID_BURAYA', 'Bir motor gaz verince "tık tık" sesi çıkarıp dönmeye başlamıyor', 'Jenerik', 'FPV Racing Drone', 'esc', 'drone', 'Dört motordan biri gaz verince hemen dönmüyor, önce "tık tık" gibi bir ses çıkarıyor, birkaç saniye sonra ya döner ya da hiç dönmez.', 'solved', 'fpv-drone-esc-senkron-hatasi-e1', now() - interval '10 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '70e84aab-daef-4286-aa69-0ce069e6892a', 'EKIP_UUID_BURAYA', 'Bu ses, fırçasız motorlarda ESC''nin motorun rotor pozisyonunu doğru algılayamadığı (senkronizasyon kaybı) durumlarda tipik olarak duyulur. Kontrol et: 1) O motora giden 3 fazlı kablolardan (genelde sarı/mavi/kırmızı renkli) biri gevşek veya kötü lehimlenmiş olabilir, lehim noktalarını görsel ve fiziksel olarak kontrol et. 2) ESC firmware ayarlarında (BLHeli vb. kullanıyorsan) motor timing veya PWM frekansı ayarı uygunsuz olabilir, motor/ESC üreticisinin önerdiği ayarlara dön. 3) Motor kendisi arızalı (sargı kısa devresi) olabilir, o motoru başka bir ESC çıkışına takıp test ederek motordan mı ESC''den mi kaynaklandığını ayırt et.', true, now() - interval '9 hours');

-- 32) Drone — RTH (eve dönüş) yanlış yöne gidiyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('f0e37dae-14b1-489e-8ce3-e953cbae0316', 'EKIP_UUID_BURAYA', '"Eve dön" fonksiyonunu tetikleyince drone kalkış noktasından farklı bir yöne gidiyor', 'Jenerik', 'GPS''li Drone', 'diger', 'drone', 'Sinyal kesilme testinde RTH (return to home) fonksiyonunu denedim, drone kalkış noktama değil tamamen farklı bir yöne uçtu.', 'solved', 'drone-rth-yanlis-yon-f2', now() - interval '9 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'f0e37dae-14b1-489e-8ce3-e953cbae0316', 'EKIP_UUID_BURAYA', 'RTH sisteminin doğru çalışması için "ev noktasının" (home point) uçuş öncesi doğru kaydedilmiş olması şart, bu genelde ilk GPS kilidi alındığı andaki konumu kaydeder. Sorunlar genelde şuralarda çıkar: 1) Drone kalkmadan ÖNCE yeterli sayıda uydu kilidi (genelde en az 8-10 uydu) almamışsa, ev noktası yanlış/hatalı kaydedilebilir; kalkmadan önce uygulamada GPS durumunu kontrol et. 2) Kalkıştan sonra ev noktası güncellenmiyor olabilir, bazı modlarda ilk açılış konumu değil "arm edilme" (motorların çalıştırılma) anındaki konum kaydedilir, bunu ayarlardan kontrol et. 3) Manyetik pusula (compass) yakınında metal/elektronik girişim varsa yön hesaplaması bozulabilir, kalkıştan önce pusulayı kalibre et ve metal yüzeylerden uzakta kalkış yap.', true, now() - interval '8 hours');

-- 33) Mini drone — menzil çok kısa kalıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('cbdfbe36-371c-4b59-aa60-cb1e8b345a9d', 'EKIP_UUID_BURAYA', 'Kutuda 50 metre yazıyor ama 15-20 metrede sinyal kopuyor', 'Jenerik', 'Mini Toy Drone', 'diger', 'drone', 'Ürün açıklamasında 50 metre menzil yazıyordu ama gerçekte 15-20 metre sonra bağlantı kopuyor ve drone otomatik iniyor.', 'solved', 'mini-drone-menzil-kisa-g3', now() - interval '8 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'cbdfbe36-371c-4b59-aa60-cb1e8b345a9d', 'EKIP_UUID_BURAYA', 'Kutu üzerindeki menzil değerleri genelde ideal laboratuvar koşullarında (açık alan, hiç parazit yok, tam şarjlı piller) ölçülür, gerçek kullanımda bu rakamlara ulaşmak zordur, özellikle giriş seviyesi/oyuncak sınıfı dronelarda. Menzili artırmak için: 1) Kalabalık wifi ortamlarından (ev içi, şehir merkezi) uzakta, açık alanda uç, wifi/bluetooth yoğunluğu bu sınıf dronelarda ciddi parazit yaratır. 2) Kumanda ve drone bataryalarının tam dolu olduğundan emin ol, düşük voltaj sinyal gücünü azaltır. 3) Kumanda anteni varsa tam açık ve dik konumda tut. Bu sınıf dronelarda gerçekçi beklenti genelde kutu değerinin %30-50''si civarındadır.', true, now() - interval '7 hours');

-- 34) RC uçak — iniş takımı sert inişte kırılıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a5a33a69-25d0-42bb-912e-039c0c8f894a', 'EKIP_UUID_BURAYA', 'Sert inişlerde iniş takımı (landing gear) sürekli kırılıyor', 'Jenerik', 'Eğitim Uçağı', 'sasi', 'ucak', 'Henüz iniş tekniğimi geliştiriyorum, sert inişlerde plastik iniş takımı bacakları sık sık kırılıyor. Aynı yerden kırılıyor genelde.', 'solved', 'rc-ucak-inis-takimi-kiriliyor-h4', now() - interval '7 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a5a33a69-25d0-42bb-912e-039c0c8f894a', 'EKIP_UUID_BURAYA', 'Öğrenme aşamasında iniş takımı kırılmaları çok yaygın, bu bir "zayıf halka" olarak tasarlanır aslında (gövdeyi korumak için önce o kırılsın diye) ama sık kırılması can sıkıcı olabilir. Öneriler: 1) Kırılan bacağı standart plastikten karbon fiber veya daha esnek kompozit bir versiyona yükseltmeyi düşün, bu tip parçalar bükülüp geri döner, kırılmaz. 2) İniş tekniğini geliştirmek asıl çözüm: inişte burnu hafif yukarıda tutup ana tekerleklerle önce dokunmak (üç nokta iniş yerine), yaklaşma hızını düşürmek darbeyi ciddi azaltır. 3) Sık kırılan aynı nokta, o bölgede bir tasarım zayıflığı olabilir, o noktayı ince bir karbon şerit veya epoksi ile takviye etmek dayanıklılığı artırabilir.', true, now() - interval '6 hours');

-- 35) Elektrikli uçak — ESC arm olmuyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('be72e9bb-0bfb-4e8e-b3e0-3982728c0392', 'EKIP_UUID_BURAYA', 'ESC''yi arm edemiyorum, motor hiç dönmüyor açılışta', 'Jenerik', 'Elektrikli Trainer Uçak', 'esc', 'ucak', 'Sistemi açtığımda ESC''nin arm (motoru çalışmaya hazır hale getirme) prosedürünü yapamıyorum, gaz kolunu ne yaparsam yapayım motor tepki vermiyor.', 'solved', 'rc-ucak-esc-arm-olmuyor-i5', now() - interval '6 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'be72e9bb-0bfb-4e8e-b3e0-3982728c0392', 'EKIP_UUID_BURAYA', 'Çoğu ESC güvenlik amaçlı, açılışta gaz kolunun kesinlikle en düşük (tam kapalı) pozisyonda olmasını ister, aksi halde arm işlemini reddeder (kazara motorun tam güçle çalışmasını önlemek için). Kontrol sırası: 1) Sistemi açmadan önce kumandanın gaz kolunun (ve varsa throttle cut/safety anahtarının) tam en düşük/kapalı konumda olduğundan emin ol. 2) Kumandayı ESC''den önce mi sonra mı açman gerektiğini kılavuzdan kontrol et, çoğu sistemde önce vericiyi (kumandayı), sonra alıcıyı/ESC''yi açma sırası önemlidir. 3) ESC''nin kendi kalibrasyonu bozulmuş olabilir, throttle range kalibrasyonunu (tam ileri-tam geri sinyalini öğretme) tekrar yap. 4) Batarya bağlantısı ve voltajı yeterli mi kontrol et, düşük voltaj bazı ESC''lerin arm olmasını engeller.', true, now() - interval '5 hours');

-- 36) Uçak — kumanda trim ayarı uçuşta kayıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('055c6ef2-5944-412c-948d-e2caaf00aa63', 'EKIP_UUID_BURAYA', 'Uçuş sırasında yatay dengeyi korumak için sürekli trim düzeltmesi gerekiyor', 'Jenerik', 'Sport Uçak', 'servo', 'ucak', 'Her uçuşta yatay düz uçuşu korumak için sürekli elevator/aileron trim ayarı yapmam gerekiyor, sabit kalmıyor, uçuş içinde de kayıyor gibi.', 'solved', 'rc-ucak-trim-kayiyor-j6', now() - interval '5 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '055c6ef2-5944-412c-948d-e2caaf00aa63', 'EKIP_UUID_BURAYA', 'Trim''in uçuş İÇİNDE kayması (yani sabit bir trim ayarının bile tutmaması) özellikle önemli bir belirti — genelde şunlardan biri: 1) Servo horn (kolu) veya kontrol yüzeyi (elevator/aileron) linkajı mekanik olarak gevşek/oynak, titreşimle kayıyor olabilir, tüm bağlantı noktalarını kontrol et ve sıkıla. 2) Servo kendisi zayıflamış/arızalı olabilir, tam tork tutamıyor olabilir. 3) Kontrol yüzeyinin menteşesi (hinge) gevşemiş veya aşırı oynak olabilir. Eğer trim sadece uçuştan uçuşa farklıysa (ama tek uçuş içinde sabit kalıyorsa) bu daha çok rüzgar/ağırlık dağılımı farkından kaynaklanır ve normal karşılanabilir, ama uçuş İÇİNDE kayıyorsa mekanik bir sorunu işaret eder.', true, now() - interval '4 hours');

-- 37) Glider — kanat bağlantı pimi kırılıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('8036772b-a95e-4e46-bf79-2b675c08f2b7', 'EKIP_UUID_BURAYA', 'Kanat bağlantı pimi (wing rod) sert inişlerde kırılıyor', 'Jenerik', 'Planör (Glider)', 'sasi', 'ucak', 'Planörümün kanat gövdeye bağlanan pimi sert inişlerde veya çarpmalarda kırılıyor, üçüncü kez oluyor bu.', 'solved', 'rc-glider-kanat-pimi-kiriliyor-k7', now() - interval '4 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '8036772b-a95e-4e46-bf79-2b675c08f2b7', 'EKIP_UUID_BURAYA', 'Kanat pimleri (genelde ahşap veya karbon çubuk) bilinçli olarak "zayıf halka" olacak şekilde tasarlanır — sert bir çarpmada önce pim kırılsın diye, böylece kanadın veya gövdenin daha pahalı/onarımı zor kısımları zarar görmez. Yani sık kırılması aslında sistemin "işini yapması" olabilir. Yine de sık kırılıyorsa: 1) Pimin malzemesini bir kademe güçlendirebilirsin (ahşaptan karbon fiber çubuğa geçmek gibi) ama bunu yaparken kanat/gövde bağlantı noktasının daha güçlü darbeyi kaldırabileceğinden emin ol, aksi halde kırılma noktası daha pahalı bir yere kayabilir. 2) İniş tekniğini yumuşatmak (yaklaşma açısını ve hızını düşürmek) kırılma sıklığını doğrudan azaltır. 3) Yedek pimden birkaç adet bulundurmak, bu parçanın sarf malzemesi olduğunu kabul edip pratik bir çözüm olarak düşünülebilir.', true, now() - interval '3 hours');

-- 38) Uçak — LiPo bağlantısı uçuşta gevşiyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('ce685e4e-4e36-420c-ab6d-5634f7419bdf', 'EKIP_UUID_BURAYA', 'Uçuş sırasında ani güç kesilmeleri yaşıyorum, batarya bağlantısından şüpheleniyorum', 'Jenerik', 'Park Flyer', 'batarya', 'ucak', 'Uçuş sırasında ara sıra ani güç kesilmesi oluyor, motor bir anlığına duruyor sonra tekrar çalışıyor. Batarya konnektörü gevşek olabilir mi diye düşünüyorum.', 'solved', 'rc-ucak-batarya-baglanti-gevsek-l8', now() - interval '3 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'ce685e4e-4e36-420c-ab6d-5634f7419bdf', 'EKIP_UUID_BURAYA', 'Ani, kısa süreli güç kesilmeleri gerçekten sıklıkla gevşek batarya konnektöründen kaynaklanır, özellikle sert manevralarda titreşim konnektörü hafif ayırabilir. Kontrol et: 1) Konnektörün (XT60 vb.) tam ve sıkı oturup oturmadığını, eski/aşınmış konnektörler zamanla gevşer, gerekirse değiştir. 2) Bataryayı gövdeye sabitleyen velcro/bant yeterince sıkı mı, uçuş sırasında batarya hafif kayıyorsa konnektöre yük biniyor olabilir. 3) Batarya kablolarının kendisinde (özellikle konnektöre yakın noktada) kırık tel/gevşek lehim olabilir, görsel kontrol et. Bu tip kesilmeleri asla göz ardı etme, uçuşta tam güç kaybı ciddi bir kaza riski taşır.', true, now() - interval '2 hours');

-- 39) Aerobatik uçak — üç eksen dengesi bozuk
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('dc18a3ed-21ee-488d-9b33-c65e29659d47', 'EKIP_UUID_BURAYA', 'Düz uçuşta bile uçak sürekli bir eksende hafif dönme eğiliminde', 'Jenerik', 'Aerobatik Uçak', 'servo', 'ucak', 'Kumandaya hiç dokunmasam bile uçak düz uçuşta yavaşça bir yöne (roll) dönmeye devam ediyor, elimi bırakamıyorum sürekli düzeltme yapmam gerekiyor.', 'solved', 'rc-ucak-uc-eksen-dengesiz-m9', now() - interval '2 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'dc18a3ed-21ee-488d-9b33-c65e29659d47', 'EKIP_UUID_BURAYA', 'Sürekli tek yöne dönme eğilimi (roll tendency) genelde birkaç sebepten olur: 1) Kanatlar arasında hafif bir açı farkı (bir kanat diğerinden farklı açıda takılmış/monte edilmiş) olabilir, kanat açılarını gözle ve bir cetvel/açıölçerle karşılaştır. 2) Aileronlardan biri tam nötrde değilse (servo merkezi kaymışsa) sürekli hafif bir kuvvet uygular, sub-trim ile düzelt. 3) Motor/pervane torku (özellikle güçlü motorlu küçük uçaklarda) doğal bir dönme eğilimi yaratabilir, bunu dengelemek için kumandada kalıcı bir trim ayarı (veya "aileron differential" ayarı varsa) kullanmak normal bir pratiktir, illa mekanik arıza olması gerekmez.', true, now() - interval '1 hours');

-- 40) Helikopter — ana rotor kalkışta sallanma
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('24769fc5-4fde-41a5-b79c-8a3c36049e9d', 'EKIP_UUID_BURAYA', 'Kalkışta helikopter şiddetli sallanıyor, havalandıkça geçiyor', 'Align', 'T-Rex 500', 'sasi', 'helikopter', 'Kalkış anında ve yere yakınken helikopter şiddetli sallanıyor (ground resonance''a benziyor), biraz yükselince sallanma geçiyor.', 'solved', 'align-trex500-kalkiste-sallaniyor-n0', now() - interval '1 hours');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '24769fc5-4fde-41a5-b79c-8a3c36049e9d', 'EKIP_UUID_BURAYA', 'Bu tanım klasik "ground resonance" (yer rezonansı) — iniş takımı/kızak ile rotor sisteminin doğal frekansları belirli bir RPM''de çakışınca şiddetli, tehlikeli bir sallanma oluşur, genelde yerden kesilirken veya inişte görülür ve HIZLA büyüyebilir, ciddi hasara yol açabilir. Önlemler: 1) İniş kızaklarının/skidlerinin sağlam ve simetrik zeminde durduğundan emin ol, eğik/tek noktadan temas eden bir zemin rezonansı tetikler. 2) Ana rotor bıçaklarının ve dampers (titreşim sönümleyiciler varsa) sağlam ve aşınmamış olduğunu kontrol et, aşınmış damperler rezonansa çok daha yatkındır. 3) Kalkışta kararsız bir bölgede (birkaç saniye) beklemeden hızlıca ya yerde kal ya da kesin bir hareketle kalk, "yarı havada" uzun süre kalmaktan kaçın. Sallanma başlarsa hemen gazı kısıp yere indirmek en güvenli tepki.', true, now() - interval '55 minutes');

-- 41) Helikopter — swashplate komutlara yanlış tepki veriyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('9e10e861-c392-476f-a20a-18892b6b9406', 'EKIP_UUID_BURAYA', 'Kumandayı ileri verince heli geri gidiyor, yönler ters gibi', 'Align', 'T-Rex 450', 'servo', 'helikopter', 'Kumandada elevator komutunu ileri verince helikopter beklediğimin tersine gidiyor. Yeni bir swashplate seti taktım geçenlerde.', 'solved', 'align-trex450-swashplate-ters-o1', now() - interval '55 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '9e10e861-c392-476f-a20a-18892b6b9406', 'EKIP_UUID_BURAYA', 'Yeni swashplate takmandan hemen sonra başlaması çok önemli bir ipucu — bu neredeyse kesin servo yönü (servo reverse) veya swashplate tipi (mixing) ayarının yanlış olduğuna işaret ediyor. Yapman gerekenler: 1) Kumandanın/flybarless kontrolcünün "swashplate type" ayarının helikopterinin gerçek tipiyle (genelde 3 servo CCPM, H1, vb.) eşleştiğinden emin ol, yanlış tip seçilirse komutlar karışır. 2) Her bir servonun yön (reverse) ayarını tek tek test et, kumandanın "servo test" veya "AFR" ekranından her kanalı ayrı ayrı hareket ettirip doğru yönde gittiğini doğrula. 3) Yeni swashplate setini takarken bağlantı çubuklarından (linkage rod) birini yanlış noktaya bağlamış olabilirsin, montaj şemasıyla tekrar karşılaştır.', true, now() - interval '50 minutes');

-- 42) Helikopter — gyro ayarı yanlış, kuyruk sürekli dönüyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('69d1d329-e8c3-40bf-a0af-ba0fe250a293', 'EKIP_UUID_BURAYA', 'Havada dururken kuyruk kendiliğinden yavaşça dönüyor, sabit kalmıyor', 'Jenerik', '450 Sınıfı Heli', 'diger', 'helikopter', 'Havada asılı dururken (hover) kuyruk sabit kalması gerekirken yavaşça bir yöne doğru dönmeye devam ediyor, sürekli pedal düzeltmesi yapmam gerekiyor.', 'solved', 'heli-kuyruk-sabit-durmuyor-p2', now() - interval '50 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '69d1d329-e8c3-40bf-a0af-ba0fe250a293', 'EKIP_UUID_BURAYA', 'Bu tam olarak kuyruk gyro''sunun (heading hold gyro) görevidir — havada sabit bir kuyruk pozisyonunu otomatik korumalı, sürekli kayma gyro ayarının yanlış olduğuna işaret eder. Kontrol et: 1) Gyro kazanç (gain) ayarı çok düşük olabilir, kademeli olarak artır (çok yüksek yaparsan bu sefer kuyruk titremeye/salınmaya başlar, dengeyi bulman gerekir). 2) Gyro''nun "heading hold" (yön tutma) modunda olduğundan emin ol, bazı gyrolar "rate mode" (sadece dönüş hızını sönümler ama pozisyonu tutmaz) ile karıştırılabilir, ayarlardan modu kontrol et. 3) Gyro yönü (normal/reverse) yanlış ayarlanmışsa gyro aslında sapmayı düzeltmek yerine büyütüyor olabilir, kuyruk servosu/motoru komutuna doğru yönde tepki veriyor mu test et.', true, now() - interval '45 minutes');

-- 43) Mini koaksiyel heli — iniş sonrası motor devri düşük kalıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('7cc69660-0da0-47d5-ab77-676e252c2196', 'EKIP_UUID_BURAYA', 'Bir iniş yaptıktan sonra motor bir daha eski gücüne çıkmıyor', 'Jenerik', 'Koaksiyel Mini Helikopter', 'motor', 'helikopter', 'Normal bir inişten sonra motoru tekrar çalıştırdığımda eskisi kadar güçlü dönmüyor, kalkış zorlaşıyor. Motoru dinlendirsem de değişmiyor.', 'solved', 'mini-heli-motor-guc-dusuk-q3', now() - interval '45 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '7cc69660-0da0-47d5-ab77-676e252c2196', 'EKIP_UUID_BURAYA', 'Kalıcı güç kaybı (dinlenmeyle düzelmiyor) genelde iki noktaya işaret eder: 1) Batarya kapasitesi o inişte/kullanımda ciddi düşmüş olabilir, özellikle küçük koaksiyel helikopterlerin bataryaları küçük ve hassastır, birkaç yüz şarj döngüsünden sonra (veya bir defalık aşırı deşarjdan sonra) kalıcı kapasite kaybı yaşayabilir — farklı, dolu bir bataryayla test et, sorun devam ediyorsa bataryadan kaynaklanmıyor demektir. 2) İnişte ana rotor mili veya dişlisi hafif eğrilmiş/zarar görmüş olabilir, bu mekanik sürtünmeyi artırıp motora fazladan yük bindirir, rotor milini elle çevirip pürüzsüzlüğünü kontrol et.', true, now() - interval '40 minutes');

-- 44) Helikopter — ESC governor modu RPM sabit tutamıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a3515605-cd9f-42a5-bfaa-e1b0278953c8', 'EKIP_UUID_BURAYA', 'Governor modunda RPM sabit kalması gerekirken manevralarda düşüyor', 'Jenerik', '600 Sınıfı Elektrikli Heli', 'esc', 'helikopter', 'ESC''yi governor moduna aldım, düz uçuşta RPM sabit ama sert manevra yaptığımda (özellikle pitch pump) RPM belirgin düşüyor ve yavaş toparlanıyor.', 'solved', 'heli-esc-governor-rpm-dusuyor-r4', now() - interval '40 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a3515605-cd9f-42a5-bfaa-e1b0278953c8', 'EKIP_UUID_BURAYA', 'Governor''ın manevra sırasında ani yük artışına (RPM düşüşüne) tepki verme hızı, governor "gain/P-gain" ayarına bağlıdır — düşük ayarlanmışsa toparlanma yavaş olur. Kontrol et: 1) ESC''nin governor gain ayarını kademeli olarak artır, sistemin daha hızlı tepki vermesini sağlar (ama çok yüksek ayarda motor titremesi/salınım başlayabilir, dengeyi bulman gerekir). 2) Batarya, o ani yükü karşılayacak kadar güçlü (yeterli C-rating/deşarj kapasitesi) değilse, motor talep ettiği akımı alamaz ve RPM düşer — bataryanın C değerinin kurulum için yeterli olduğunu doğrula. 3) Pitch pump gibi çok agresif manevralar her sistemde bir miktar RPM düşüşüne sebep olur, tamamen sıfıra indirmek zor olabilir, makul bir toparlanma süresi normal kabul edilir.', true, now() - interval '35 minutes');

-- 45) RC tekne — pervane şaftı eğrilmiş titreşim yapıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('8ba1cf9c-d77c-493d-ac32-a7756efb4466', 'EKIP_UUID_BURAYA', 'Sudan sonra tekne gövdesinde belirgin bir titreşim var, pervanede olabilir mi?', 'Jenerik', 'RC Sürat Teknesi', 'sasi', 'tekne', 'Suda giderken tekne gövdesi elle hissedilir şekilde titriyor, hız arttıkça titreşim de artıyor. Pervaneye çarpma olmuştu geçen kullanımda.', 'solved', 'rc-tekne-pervane-sifti-egik-s5', now() - interval '35 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '8ba1cf9c-d77c-493d-ac32-a7756efb4466', 'EKIP_UUID_BURAYA', 'Bir çarpma sonrası başlayan, hızla artan titreşim neredeyse kesin olarak pervane şaftının (drive shaft) eğrilmesine işaret ediyor — düz bir yüzeyde şaftı yuvarlayarak (veya elle dikkatlice hissederek) eğrilik var mı kontrol et, çok küçük bir eğrilik bile yüksek devirde ciddi titreşim yaratır. Şaft eğriyse düzeltmeye çalışma (genelde kalıcı zarar bırakır, tekrar eğrilmeye meyilli kalır), yenisiyle değiştirmek en güvenli çözüm. Ayrıca pervanenin kendisi de çarpmada hafif deforme olmuş/eğrilmiş olabilir, pervaneyi de gözden geçir, gerekirse onu da değiştir. Şaft tüpü (stuffing tube) içindeki yataklar da çarpmadan etkilenmiş olabilir, kontrol etmeden atlama.', true, now() - interval '30 minutes');

-- 46) RC tekne — ESC su geçirmezliği bozulmuş, kısa devre yapıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('5d8355c9-b870-4ba4-b2db-c81f59cbdb62', 'EKIP_UUID_BURAYA', 'Tekne suya girdikten kısa süre sonra tamamen elektroniği gitti', 'Jenerik', 'RC Sürat Teknesi', 'esc', 'tekne', 'Yeni aldığım teknede birkaç kullanımdan sonra ESC tamamen tepkisiz kaldı, gövdeyi açtığımda hafif nem/yoğuşma izi vardı içeride.', 'solved', 'rc-tekne-esc-su-kisa-devre-t6', now() - interval '30 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '5d8355c9-b870-4ba4-b2db-c81f59cbdb62', 'EKIP_UUID_BURAYA', 'Nem/yoğuşma izi, elektronik kutusunun tam su geçirmez olmadığının veya nemin zamanla (dışarıdan direkt su girmeden bile) sızdığının işareti — teknelerde bu en sık karşılaşılan arıza sebeplerinden biri. Ne yazık ki suya maruz kalmış bir ESC genelde onarılamaz, korozyon devre kartına yayılır; en güvenli yol yeni (tercihen özel olarak "waterproof/marine" olarak işaretlenmiş) bir ESC almak. Gelecekte önlem olarak: 1) Elektronik kutusunun contasını her kullanım öncesi kontrol et, sıkı kapandığından emin ol. 2) Kutunun içine küçük bir nem alıcı (silika jel) paketi koymak yoğuşmayı azaltır. 3) Her kullanımdan sonra gövdeyi açık bırakıp içerdeki nemin tamamen kurumasına izin ver, hemen kapatıp kaldırma.', true, now() - interval '25 minutes');

-- 47) RC tekne — dümen servosu suya karşı zayıf kalıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('cbcb27b0-0836-429c-a42c-3e9b4a53b5f9', 'EKIP_UUID_BURAYA', 'Yüksek hızda dümen komutlarına yeterince güçlü tepki veremiyor', 'Jenerik', 'RC Sürat Teknesi', 'servo', 'tekne', 'Yavaş hızda dümen sorunsuz çalışıyor ama yüksek hızda su direnci fazla geliyor sanırım, dümen komutlarına zayıf/yavaş tepki veriyor.', 'solved', 'rc-tekne-dumen-servo-zayif-u7', now() - interval '25 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'cbcb27b0-0836-429c-a42c-3e9b4a53b5f9', 'EKIP_UUID_BURAYA', 'Yüksek hızda su akışının dümen üzerinde oluşturduğu direnç ciddi olabilir, standart bir araç/uçak servosu bu yükü kaldırmakta zorlanabilir. Çözümler: 1) Daha yüksek tork değerine sahip, tercihen "marine/tekne" kullanımı için üretilmiş metal dişlili bir servoya yükselt, standart plastik dişli servolar bu tip sürekli yüke uzun vadede dayanamaz. 2) Dümen bıçağının boyutu tekne için fazla büyükse gereğinden fazla direnç oluşturabilir, üretici tavsiyesine uygun boyutta olduğundan emin ol. 3) Dümen linkajının sürtünmesiz, pürüzsüz hareket ettiğinden emin ol, herhangi bir sürtünme servonun etkin gücünü daha da azaltır.', true, now() - interval '20 minutes');

-- 48) RC tekne — batarya suya değince şişmiş
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('49131bf3-6789-4a1e-8bd5-236726590151', 'EKIP_UUID_BURAYA', 'Gövdeye su kaçmış, batarya da bundan etkilenip şişmiş görünüyor', 'Jenerik', 'RC Sürat Teknesi', 'batarya', 'tekne', 'Geçen kullanımda gövdeye biraz su kaçmıştı, şimdi bataryayı çıkarınca hafif şişmiş ve ıslak görünüyor. Ne yapmalıyım?', 'solved', 'rc-tekne-batarya-su-sismis-v8', now() - interval '20 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '49131bf3-6789-4a1e-8bd5-236726590151', 'EKIP_UUID_BURAYA', 'GÜVENLİK UYARISI: Suyla temas etmiş ve şişmiş bir lipo bataryayı kesinlikle şarj etme veya kullanmaya devam etme, hem şişme hem de suyla temas ayrı ayrı ciddi risk taşır, ikisi birlikte daha da tehlikelidir (su, hücre içindeki kimyasallarla tepkimeye girip ısı/gaz üretebilir). Bataryayı hemen yanıcı olmayan, güvenli bir alana (metal kutu, dışarıda) koy ve gözlemle (aşırı ısınma, şişmenin artması var mı). Güvenli görünse bile bir daha kullanma, tuzlu suda bekletme yöntemiyle güvenli şekilde imha et. Gelecek için: gövde su geçirmezliğini (conta, kablo girişleri) düzelt ve batarya bölmesini ayrıca su geçirmez bir torba/kutu içine almayı düşün, teknelerde bu ekstra bir güvenlik katmanı sağlar.', true, now() - interval '15 minutes');

-- 49) Genel — şarj cihazı hücre sayısını (S) yanlış algılıyor
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('a2929746-95f2-4c77-a78e-ec9e8e769854', 'EKIP_UUID_BURAYA', 'Şarj cihazı 3S bataryayı 2S olarak algılıyor, otomatik algılama yanlış', 'Genel', 'Evrensel Lipo Şarj Cihazı', 'batarya', 'diger', 'İki farklı 3S bataryamı taktığımda şarj cihazı otomatik hücre algılamada bazen yanlışlıkla 2S gösteriyor. Manuel seçmem gerekiyor her seferinde.', 'solved', 'lipo-sarj-hucre-sayisi-yanlis-w9', now() - interval '15 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), 'a2929746-95f2-4c77-a78e-ec9e8e769854', 'EKIP_UUID_BURAYA', 'Otomatik hücre algılama (auto cell detect), balance konnektöründeki her bir hücre ucundaki voltajı okuyarak çalışır — eğer balance konnektöründeki pinlerden biri kirli/oksitlenmiş veya tam temas etmiyorsa, cihaz bir hücreyi göremez ve yanlış sayı algılar. Kontrol et: 1) Balance konnektörünün pinlerini (hem batarya hem şarj cihazı tarafında) temizle, ince bir fırça veya kontak temizleyici kullanılabilir. 2) Konnektörün tam oturduğundan emin ol, yarım takılı konnektör en sık sebeptir. 3) Bataryanın hücrelerinden biri aşırı düşük voltaja inmişse bazı cihazlar bu hücreyi "yok" sayabilir, bataryayı manuel modda dikkatli şekilde şarj etmeyi dene. Bu sorun sürekli tekrarlıyorsa güvenlik açısından her zaman manuel modda ve doğru hücre sayısını seçerek şarj etmek en güvenlisidir, otomatik algılamaya asla körü körüne güvenme.', true, now() - interval '10 minutes');

-- 50) Genel — firmware güncelleme sonrası kumanda tepkisiz kaldı
insert into problems (id, user_id, title, brand, model, category, vehicle_type, description, status, slug, created_at) values
('32b9bb82-ef4b-492d-a7b6-275e5bebe22a', 'EKIP_UUID_BURAYA', 'Kumandaya firmware güncellemesi yaptıktan sonra araçla hiç bağlantı kuramıyorum', 'Genel', 'Programlanabilir 2.4GHz Kumanda', 'diger', 'diger', 'Kumandamın firmware''ini güncelledim, güncelleme "başarılı" diye bitti ama artık hiçbir aracımla/alıcımla bağlantı (bind) kuramıyorum.', 'solved', 'kumanda-firmware-sonrasi-tepkisiz-x0', now() - interval '10 minutes');
insert into answers (id, problem_id, user_id, body, is_accepted, created_at) values
(gen_random_uuid(), '32b9bb82-ef4b-492d-a7b6-275e5bebe22a', 'EKIP_UUID_BURAYA', 'Firmware güncellemesi sonrası bağlantı sorunları genelde şu sebeplerden olur: 1) Yeni firmware, bind (eşleştirme) protokolünü değiştirmiş olabilir, eski eşleştirmeler artık geçerli değildir — her alıcıyla YENİDEN bind işlemi yapman gerekiyor, bu bir arıza değil beklenen bir adım olabilir. 2) Güncelleme sırasında bağlantı kesilmiş/yarım kalmışsa (örneğin USB/güç kaybı), firmware bozulmuş (corrupt) olabilir, kumandanın "bootloader/recovery" moduna girip firmware''i baştan yüklemen gerekebilir, üreticinin kılavuzuna bak. 3) Bazı firmware sürümleri belirli alıcı protokollerini kaldırmış/değiştirmiş olabilir, kullandığın alıcının hâlâ desteklendiğini üretici notlarından (changelog) doğrula. Sorun devam ederse, mümkünse bir önceki kararlı firmware sürümüne geri dönmek (downgrade) de bir seçenek olabilir.', true, now() - interval '5 minutes');
